### ISSUE TITLE
Order of media queries 

### ISSUE THREAD

**Issue by MadeByMike** [seek-oss/vanilla-extract#141]
### Describe the bug

Sometimes media queries appear to be in the wrong order in the CSS:

![image](https://user-images.githubusercontent.com/1320567/118382301-5d515580-b637-11eb-8dcd-c30311a33687.png)

Here are the declarations (I'd expect same order as when created?):

![image](https://user-images.githubusercontent.com/1320567/118382309-67735400-b637-11eb-9da5-90b5b9352b71.png)

What I find odd about this is that changing the media queries to remove the `screen and` part sometimes appears to fix it.

![image](https://user-images.githubusercontent.com/1320567/118382317-870a7c80-b637-11eb-8f62-8eb12b13f3ba.png)

But then changing other declarations may cause it to return. Perhaps some funny shenanigans are happening with order when objects are merged to cloned? 

I'm having trouble isolating a small consistent reproduction case although I can reproduce reliably in my project.

### System Info

I'm using vanilla, vanilla extract here with no other abstractions apart from a few variables for tokens. I'm working in a mono repo with a Gatsby site where my components are stored in a different package.

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: Linux 4.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 4.84 GB / 15.95 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.16.3/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
```

**Comment by MadeByMike** [comment]
I found some more evidence of stuff it was miss-writing:

![image](https://user-images.githubusercontent.com/1320567/118384291-4bc47980-b648-11eb-92ed-d01008670597.png)

**Comment by markdalgleish** [comment]
I'm pretty confident that this is because we merge media queries together at the file level as an optimisation. I've been able to create a minimal reproduction: https://codesandbox.io/s/icy-cloud-j40qh?file=/src/App.css.ts

My gut reaction is that this may be something we need to pull from vanilla-extract because it's clearly an unsafe optimisation. Now that we have Sprinkles, it might make more sense to put this optimisation there since we can also do it safely in that context.

**Comment by markdalgleish** [comment]
We're actively looking to fix this. Still working through it, but we're hoping that we can still automatically merge media queries, but bail out of the optimisation if we detect that it will cause issues.
