### ISSUE TITLE
Question - targeting child nodes best practise

### ISSUE THREAD

**Issue by brendanmckenzie** [seek-oss/vanilla-extract#15]
If I have, for example, a list:

```html
<ul>
  <li>item 1</li>
  <li>item 2</li>
  <li>item 3</li>
</ul>
```

Normally I would create a class for the `<ul class="list" />` and then target the items with `.list > li`.

With this library - would I be better off using `globalStyle('${list} > li', {})` or applying a class to each `<li />` ?

**Comment by markdalgleish** [comment]
My personal preference would be to use a class for the li elements since there's less indirection, makes it easier to see which elements are styled when looking at the markup, and makes it easier to detect unused styles too. That said, it's really up to you.
