### ISSUE TITLE
Development (HMR) issues when using Vite

### ISSUE THREAD

**Issue by sandgraham** [seek-oss/vanilla-extract#190]
### Describe the bug

I'm using vanilla-extract with a Vite/React/TS project and I've run into a couple issues while in development.

---

**If you remove a style declaration, it still applies to elements using that class.**

Let's say you have a declaration like `alignItems: "center"` in your class definition and assign it to a div. If you remove that `alignItems` declaration and save, it'll still apply to the div after HMR.

Looking at the styles panel in devtools, it seems to be because class names are not changed between saves- a new style definition for the class is added to the page while the previous one remains. The `alignItems` declaration is picked up due to the cascade.

<img width="415" alt="Screen Shot 2021-06-07 at 7 33 56 PM" src="https://user-images.githubusercontent.com/1939257/121114943-4da5d680-c7c9-11eb-82fc-58365678003b.png">

I'm not sure if that is expected, but it does make it a bit harder to iterate on styling while in development.

---

The second issue is, I think, probably what is documented in the [Vite Setup section](https://vanilla-extract.style/documentation/setup/#vite), but just wanted to verify.

**If I update a theme property in one file, it'll update in a dependent `.css.ts` file until I set the property back to it's original value.**

For example, if I set a theme value `brand: 'mediumslateblue'` in `theme.css.ts`, and use that in `styles.css.ts` everything is dandy. If I change `brand` to `'pink'` and save, the HMR works as expected. I can keep changing the value and saving and things work as expected- until I set the value back to the original `mediumslateblue`. Refreshing the page seems to "reset" this behavior.

_Note: There is no cascade issue as in the previous issue- at least none apparent in devtools._

---

The combination of the two issues means I'm never quite sure if the browser is showing the right thing so I end up refreshing the page a lot just in case. I'm not sure if both of these issues stem from the same [Vite limitation](https://github.com/vitejs/vite/issues/3216) but if so, I'll prob just have to wait to use vanilla-extract with this particular project.

This is sad because I **love** the overall API. I just can't ask my team to put up with the current dev experience resulting from these two issues (and we can't change Vite at this point). I think if the first issue was cleared up we might be able to go ahead since the second issue only really matters while changing a theme (which shouldn't happen often).

Anyways, thanks for your work on this project - it really is an ideal combination of features.

### Link to reproduction

https://github.com/sandgraham/vanilla-extract-vite-issue

_This is a freshly scaffolded Vite/React/TS project with some minimal vanilla-extract setup._

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 11.3.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 1.42 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.77
    Chrome Canary: 93.0.4535.0
    Firefox Developer Edition: 87.0
    Safari: 14.1
    Safari Technology Preview: 14.2
  npmPackages:
    @vanilla-extract/css: ^1.0.0 => 1.0.0 
    @vanilla-extract/vite-plugin: ^1.0.0 => 1.0.0 
    vite: ^2.0.5 => 2.3.6 
```

**Comment by mattcompiles** [comment]
Hey Bud 👋 

Thanks for the clear issue report. I can see what you're talking about. I'm not sure why the old CSS definitions are hanging around TBH. The issue could be on our end or with Vite. 

However, given that we currently have a few outstanding issues with the Vite implementation I'm considering swapping out their default CSS behaviour in favour of vanilla-extract's built-in runtime. I need to do some more testing before committing to this approach though.

**Comment by andrewgreenh** [comment]
I just upgraded vanilla extract packages and vite and first tests seem to indicate that these problems are now solved :)

Upgraded the follow packages:
- @vanilla-extract/css from 1.2.2 to 1.2.3
- @vanilla-extract/vite-plugin from 1.1.1 to 1.1.2
- vite from 2.4.4 to 2.5.0

**Comment by mattcompiles** [comment]
Thanks @andrewgreenh. I just had a quick look as well and I'm not seeing the issues either. 🙌
