### ISSUE TITLE
Docs clarification - globalStyle is only compatible with plain style() parent classes

### ISSUE THREAD

**Issue by Brendan-csel** [seek-oss/vanilla-extract#191]
### Possibly a note for the docs?...
Using `globalStyle()` based on a parentClass created from `style()` is fine...

``` ts
export const parentClass = style({});

globalStyle(`${parentClass} > a`, {
  color: 'pink'
});
```
...but if parentClass is created using `composeStyles()` (or `atoms()`?) then it can no longer work with `globalStyle()` as it is no longer just a single class name.

Obvious I guess but I stumbled on this when I changed a parent class from `style()` to `composeStyles()` and the related `globalStyles()` stopped getting applied.  

(If you're curious about why we were using `globalStyle()` it was for applying some table `tr` and `td` styles based on an overall table class and we didn't want to add lots of specific class names on those elements)

**Comment by Brendan-csel** [comment]
As we learn about a project like this, things that were initially confusing become so obvious that we forget why they were confusing in the first place.  

While I still remember, I wanted to write down here _why_ I initially found this confusing.

Upon reflection it was because I didn't immediately grasp that functions like `composeStyles()` (and `atoms()`) were returning multiple concatenated class names.  I guess I was thinking they were somehow returning some single "composite" class name instead of the much simpler reality.

Although my comment and PR are related to `globalStyle()`  it may also be possible to add a few words to the `composeStyles()` docs just to really call this out for the slower folks like me. 😜  The existing phrase "Combines multiple styles into a single class string" possibly gave me the slightly wrong impression during my first skim read of the docs.

Anyway, I'm definitely no "docs writer" and gladly leave that to someone else in my business - but thought I'd throw down these comments in case they help give an "outsider's perspective".

As always, thanks very much for putting this project together and good luck with all that beta work I see the team doing over in the Braid repo!

**Comment by Amareis** [comment]
I think this is related to type-safe selectors discussion. Plain strings interpolation is definitely not a type-safe and we need a some higher level primitives, such as SingleClassName, ClassNamesString and so on...

**Comment by Brendan-csel** [comment]
Solved with recent composeStyles change -thank you! :)
