### ISSUE TITLE
Add `createVarName` for creating scoped CSS vars

### ISSUE THREAD

**Issue by visualfanatic** [seek-oss/vanilla-extract#2]
I was really looking forward to see what you have been working on and I am super excited to try it out in my project that currently uses Emotion :)

Currently the `createVar` function generates a variable name and then returns it wrapped in `var(...)`. This makes it easier to reference a scoped CSS var in `style` blocks, but at the same time makes it a bit trickier to set its value outside of a `.css.ts` file.

Would you consider adding a new function, for example called `createVarName`, that just returns a variable name?

Here is a pseudo-example of usage:
```ts
// component.css.ts
import { createVarName, style } from '@vanilla-extract/css';

export const positionVar = createVarName();

export const box = style({
  transform: `translate3d(var(${positionVar}), 0, 0)`,
});
```

```tsx
// component.ts
import { useRef, useState } from 'react';
import * as styles from './component.css';

export default function SomeComponent() {
  const boxRef = useRef<HTMLDivElement>(null);
  const [currentIndex, setCurrentIndex] = useState(0);

  useLayoutEffect(() => {
    if (boxRef.current) {
      boxRef.current.style.setProperty(
        styles.positionVar,
        `${currentIndex * 1000}px`,
      );
    }
  }, [currentIndex]);

  return (
    <div className={styles.box} ref={boxRef}>
      ...
    </div>
  );
}
```

**Comment by markdalgleish** [comment]
I'd probably model this as something like `getVarName` that accepts a var created by vanilla-extract.

**Comment by markdalgleish** [comment]
We could potentially also provide runtime APIs for setting vanilla vars on elements.

**Comment by markdalgleish** [comment]
On that last point, thinking we could provide APIs like this:

```ts
setElementVar(el, themeVars.mode, 'dark')

assignElementVars(el, themeVars.space, {
  small: '4px',
  medium: '8px',
  large: '12px'
})
```

**Comment by duarten** [comment]
I think I have another use case for such an API. Consider a `Responsive<Height>>`, given 

```ts
interface Responsive<T> { mobile: T, tablet: T, desktop: T }

type Height = 1 | 2 | 3 ... | "full"
```

To minimize the amount of classes generated, we could want to generate the following styles:

```ts
export const heightMobileVar = createVar();
export const heightTabletVar = createVar();
// ...
export const responsiveHeight = style({
  '@media': {
    'screen': {
      height: heightMobileVar,
    },
    'screen and (min-width: 768px)': {
      height: heightTabletVar 
    },
    // ...
  },
});
```

In my component, I would map from `Responsive<Height>` to an assignment of theme values to those height variables. Something like the following:

```ts
// Theme values
const heights = {
  1: "1px",
  2: "2px",
  // ...
  fill: "100%",
} as const;

// createVars would be a new API
const heightVars: Record<screens, string> = createVars({ ... });

// assignVars would return a CSSProperties object.
<Component style={assignVars(heightVars, mapResponsive(heightProp, asLookup(heights))) ... />
```

**Comment by mattcompiles** [comment]
@duarten I think your use-case is already catered to by the [`createInlineTheme`](https://github.com/seek-oss/vanilla-extract#createinlinetheme) API?

**Comment by markdalgleish** [comment]
Opened a PR for imperatively setting vars on elements at runtime: https://github.com/seek-oss/vanilla-extract/pull/25

**Comment by visualfanatic** [comment]
@markdalgleish thank you! I think we can close this issue.
