### ISSUE TITLE
Support for :is and :where selectors inside style.

### ISSUE THREAD

**Issue by mattcompiles** [seek-oss/vanilla-extract#202]
### Discussed in https://github.com/seek-oss/vanilla-extract/discussions/201

<div type='discussions-op-text'>

<sup>Originally posted by **minht11** June 20, 2021</sup>
Could support be added for [`:is` selector](https://developer.mozilla.org/en-US/docs/Web/CSS/:is), so use case like this would work:

```js
style({
  background: 'red',
  selectors: {
    '&:is(:focus-within, :hover)': {
      background: 'blue',
    }
  }
})
```
There probably would be some restrictions to it, but since `:is` selector references element itself it shouldn't be too much of a problem.
You can use `globalStyle` as an alternative right now, but it doesn't feel as clean.</div>

**Comment by markdalgleish** [comment]
@minht11 Fixed in `v1.0.1` of `@vanilla-extract/css`
