### ISSUE TITLE
Cannot find module '@vanilla-extract/css/disableRuntimeStyles'

### ISSUE THREAD

**Issue by dagda1** [seek-oss/vanilla-extract#217]
### Describe the bug

According to the README, in order to disable runtime styles, I need to add this to the jest `setupTests` file

```ts
import '@vanilla-extract/css/disableRuntimeStyles';
```

### Link to reproduction

```bash
npm install @vanilla-extract/css
node
require('@vanilla-extract/css/disableRuntimeStyles')  // Cannot find module '@vanilla-extract/css/disableRuntimeStyles'
```

The files section of `@vanilla-extract/css` has a number of files that are not actually pointing to a correct location:

```
  "files": [
    "/dist",
    "/recipe",
    "/adapter",
    "/transformCss",
    "/fileScope",
    "/disableRuntimeStyles"
  ],
  ```

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Memory: 36.04 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.volta/tools/image/node/14.16.0/bin/node
    Yarn: 1.22.0 - ~/.volta/tools/image/yarn/1.22.0/bin/yarn
    npm: 6.14.11 - ~/.volta/tools/image/node/14.16.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0
    Safari: 14.1.1
```

**Comment by dagda1** [comment]
I've created a [codesandbox](https://codesandbox.io/s/vanilla-extract-first-step-forked-w0v4f?file=/src/setupTests.ts) that illustrates the problem.  You need to create a new terminal and run `yarn test`

**Comment by mattcompiles** [comment]
That codesandbox points to a version of vanilla-extract before `disableRuntimeStyles` was added. Updating it causes the issue to go away.
