### ISSUE TITLE
pseudo selector not being applied

### ISSUE THREAD

**Issue by dagda1** [seek-oss/vanilla-extract#218]
### Describe the bug
I have this rule

```ts
export const required = style({
  ":before": {
    content: "*",
    marginRight: vars.space["1x"]
  }
});
```

But the rule is not coming through in the css.

### Link to reproduction
Here is a [codesanbox](https://codesandbox.io/s/vanilla-extract-first-step-forked-w0v4f?file=/src/components/atoms/label/Label.css.ts:307-339) that shows the problem.

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Memory: 36.04 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.volta/tools/image/node/14.16.0/bin/node
    Yarn: 1.22.0 - ~/.volta/tools/image/yarn/1.22.0/bin/yarn
    npm: 6.14.11 - ~/.volta/tools/image/node/14.16.0/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0
    Safari: 14.1.1
```

**Comment by markdalgleish** [comment]
Hey! Thanks for the sandbox. There are a couple of issues:
- When `content` values require quotes in CSS, you unfortunately need to double quote it—once of JS, then once for CSS, e.g. `content: '"*"',`
- In your app, you needed to pass the `required` prop to the `Label` component.

Here's an updated sandbox: https://codesandbox.io/s/vanilla-extract-first-hacks-in-forked-yj9f3?file=/src/components/atoms/label/Label.css.ts
