### ISSUE TITLE
Declarative way of setting inline variable

### ISSUE THREAD

**Issue by graup** [seek-oss/vanilla-extract#245]
We have `setElementVar` to set a var on a DOM element. But how about a more declarative way to assign the var using inline styles? I tried to do something like

```
const currentValue = createVar();
const style = {[currentValue]: `${100 * percentage}%`};
return <div style={style} />
```

which obviously doesn't work because `currentValue` is `"var(--currentValue-xyz)"`. Is there another way to do this?

**Comment by graup** [comment]
Ok, of course I found a way just after I posted this :D

It's a little bit verbose but it works. We could consider adding a little less verbose API for this:

```ts
const currentValue = createVar();

const dynamicStyles = createInlineTheme({
  currentValue,
}, {
  currentValue: `${100 * percentage}%`,
});
return <div style={style} />
```

Or at least add an example like this to the docs :)

**Comment by everdimension** [comment]
The solution looks really excessive and uses lots of jargon which is alien to css language

My use case is exposing some props which are styled with custom properties, e.g.:

```jsx
import { styles, trackColorVar } from './styles.css' // a vanilla-extract file

export function Spinner({ trackColor }: { trackColor?: string }) {
  return <div className={styles} style={{ [trackColorVar]: trackColor }}/>
}
```

Also bringing in `@vanilla-extract/dynamic` looks like unnecessary we're bringing unnecessary runtime code where it's not really needed.

**Comment by markdalgleish** [comment]
@graup I really like your `assignInlineVars` API—seems super obvious in hindsight since it mirrors the `vars` property on style objects. I've taken this as inspiration to streamline the entire `dynamic` API into two functions in the PR linked above.

**Comment by markdalgleish** [comment]
New API is out in [`@vanilla-extract/dynamic@2.0.0`](https://github.com/seek-oss/vanilla-extract/releases/tag/%40vanilla-extract%2Fdynamic%402.0.0)
