### ISSUE TITLE
Compatibility with IE11

### ISSUE THREAD

**Issue by jcze91** [seek-oss/vanilla-extract#249]
Hello,

The lib looks awesome, but I've one question given that the library uses CSS Variables : is the library compatible with IE 11 ?

Thanks

**Comment by markdalgleish** [comment]
Just like regular CSS, this library works with IE11 but certain features may not work. Unfortunately, this means all dynamic theming features are unavailable.

**Comment by codemilli** [comment]
@markdalgleish 
What if IE11 is fine with just the default theme, without any dynamic css changes?
