### ISSUE TITLE
How to use in an external package consumed by other projects?

### ISSUE THREAD

**Issue by mattfelten** [seek-oss/vanilla-extract#268]
Reading the docs I see how to get set up and seems pretty straightforward for one project. 

How do you recommend setting this up where the theme and CSS would be in project-one which is published and then consumed by project-two/three/etc (think design system)? I could see either needing to compile before publishing or needing to have any consumer project adjust their build setup. Do you have any guides for this type of setup?

**Comment by TheComputerM** [comment]
I too would like to know more about this, maybe like a ContextProvider in vanilla-extract.
