### ISSUE TITLE
NullableTokens type definition question

### ISSUE THREAD

**Issue by kandl** [seek-oss/vanilla-extract#269]
Hello, first thanks for the great library!

In examples, I see this:
```
export const vars = createThemeContract({
  color: {
    brand: null
  },
  font: {
    body: null
  }
});
```

but NullableTokens are defined like this:

```
export type NullableTokens = {
  [key: string]: string | Tokens | null;
};
```

So in TypeScript strict mode, example is failing on a wrong typing.
Should it be rather defined like this
```
export type NullableTokens = {
  [key: string]: string | NullableTokens | null;
};
```
Or am I missing something?
I can create PR for it, but maybe I'm just misunderstanding it. (I've only been playing with this lib for a few days).

**Comment by markdalgleish** [comment]
Thanks for raising this! Fixed in [`@vanilla-extract/css@1.2.2`](https://github.com/seek-oss/vanilla-extract/releases/tag/%40vanilla-extract%2Fcss%401.2.2)
