### ISSUE TITLE
Targetting attribute selectors with value: '&:[data-state="on"]' throws compilation error.

### ISSUE THREAD

**Issue by gafemoyano** [seek-oss/vanilla-extract#285]
### Describe the bug
A common pattern when using React 'primitive' libraries such as [radix](https://www.radix-ui.com/docs/primitives/components/collapsible) or [reach-ui](https://reach.tech/styling) is to allow styling the component on a given state targetting an attribute and it's value, example:

```css
[data-reach-combobox] {
}

/* root element in a specific state  */
/* possible states: "idle" | "suggesting" | "navigating" | "interacting"  */
[data-reach-combobox][data-state="STATE_REF"] {
}
```
Using vanilla extract, targetting attributes works just fine but a specific value results in an `Error: Invalid selector: '&[data-state]="on"'`:

```ts
export const panel = style({
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  borderWidth: '1px',
  selectors: {    
    '&[data-state]="on"': {
      //this throws an error
    },
    '&[data-state]': {
      //this works fine
    },
  },
})

```

### Link to reproduction
I think this does it:
https://codesandbox.io/s/kind-brook-sl451?file=/src/App.css.ts:505-569
### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
System:
    OS: Linux 5.4 Linux Mint 20.2 (Uma)
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 9.54 GB / 31.33 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.19.0 - ~/.config/nvm/12.19.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 7.11.1 - ~/.config/nvm/12.19.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 90.0.2
  npmPackages:
    @vanilla-extract/css: ^1.2.1 => 1.2.1 
    @vanilla-extract/sprinkles: ^1.0.0 => 1.0.0 
    @vanilla-extract/webpack-plugin: ^1.1.0 => 1.1.0
```

**Comment by gafemoyano** [comment]
Nevermind it was actually a typo :sweat_smile: it shou'd have been written as:

```ts
selectors:{
  '&[data-state="on"']': {
      ...
   }
}
```

**Comment by Ghirigoro** [comment]
I'm having the same issue but I'm not sure I understand what your solution is. That's not valid JS...
```
selectors:{
  '&[data-state="on"']': { <-- This is a syntax error. You have an orphaned bracket followed by an orphaned single quote
      ...
   }
}
```
Also the version with just the attribute name gives me a compilation error as well:
```    
'&[data-state]': {
      //this works fine <-- Not for me
},
```

**Comment by askoufis** [comment]
@Ghirigoro I've tested both of the above scenarios, and as long as you're careful to match quotes and brackets, both should work:

```tsx
// MyComponent.css.ts
import { style } from '@vanilla-extract/css';

export const myStyle = style({
  selectors: {
    '&[data-state="on"]': {
      color: "red",
    },
    "&[data-state]": {
      fontSize: "24px",
    },
  },
});

// MyComponent.tsx
import { myStyle } from "./MyComponent.css";

export const MyComponent = () => (
  <div className={myStyle} data-state="on">
    Hello world
  </div>
);
```

With the example code above, the result is that the `Hello world` text is both red and 24px.

Could you paste the entire style you're writing as well as how you're consuming the classname in your component? Alternatively, if this is a bug and you can make a minimal reproduction, please raise an issue.

**Comment by Ghirigoro** [comment]
After a bit it just started working for me. I can only assume it was some problem with a cache or with Vite somewhere. Apologies for the false alarm and thanks for the response

**Comment by resetmerlin** [comment]
now this syntax is not gonna be work.
```tsx
    "&[data-state]": {
      fontSize: "24px",
    },
```

u have to declare as a global style. 

or 

```tsx
    '[data-state="open"] &': {
      fontSize: "24px",
    },
```
