### ISSUE TITLE
Getting TypeError: this.getOptions is not a function

### ISSUE THREAD

**Issue by tawhidurrahman** [seek-oss/vanilla-extract#296]
### Describe the bug

I'm using vanilla-extract with a CRA typescript template project with craco for overriding react-script and I've run into a issue while in development.

I'm getting the error shown below when using `btn` styles in `App.tsx`

`./node_modules/@vanilla-extract/webpack-plugin/extracted/dist/vanilla-extract-webpack-plugin-extracted.cjs.js (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/virtual-resource-loader/dist/virtual-resource-loader.cjs.js?{"source":"OnJvb3QgewogIC0tZm9udC1mYW1pbHlfXzFreTN3dHEwOiAnTW9udHNlcnJhdCcsICdIZWx2ZXRpY2EgTmV1ZScsICBBcmlhbCwgc2Fuc3NlcmlmICFkZWZhdWx0OwogIC0tZm9udC1zaXplLXBhcmFncmFwaF9fMWt5M3d0cTE6IDEuMmVtICFkZWZhdWx0OwogIC0tZm9udC1zaXplLW5hdmJhcl9fMWt5M3d0cTI6IDFlbSAhZGVmYXVsdDsKICAtLWZvbnQtc2l6ZS1taW5pX18xa3kzd3RxMzogMC43MTQyZW0gIWRlZmF1bHQ7CiAgLS1mb250LXNpemUtc21hbGxfXzFreTN3dHE0OiAwLjg1NzFlbSAhZGVmYXVsdDsKICAtLWZvbnQtc2l6ZS1iYXNlX18xa3kzd3RxNTogMTRweCAhZGVmYXVsdDsKICAtLWZvbnQtc2l6ZS1sYXJnZV9fMWt5M3d0cTY6IDFlbSAhZGVmYXVsdDsKICAtLWZvbnQtc2l6ZS1sYXJnZU5hdmJhcl9fMWt5M3d0cTc6IDIwcHggIWRlZmF1bHQ7CiAgLS1mb250LXNpemUtYmxvY2txdW90ZV9fMWt5M3d0cTg6IDEuMWVtICFkZWZhdWx0OwogIC0tZm9udC13ZWlnaHQtbGlnaHRfXzFreTN3dHE5OiAzMDAgIWRlZmF1bHQ7CiAgLS1mb250LXdlaWdodC1ub3JtYWxfXzFreTN3dHFhOiA0MDAgIWRlZmF1bHQ7CiAgLS1mb250LXdlaWdodC1zZW1pX18xa3kzd3RxYjogNjAwICFkZWZhdWx0OwogIC0tZm9udC13ZWlnaHQtYm9sZF9fMWt5M3d0cWM6IDcwMCAhZGVmYXVsdDsKICAtLWZvbnQtbGluZUhlaWdodC1nZW5lcmFsX18xa3kzd3RxZDogMS41ICFkZWZhdWx0OwogIC0tZm9udC1saW5lSGVpZ2h0LW5hdkxpbmtfXzFreTN3dHFlOiAxLjYyNXJlbSAhZGVmYXVsdDsKICAtLWZvbnQtbGluZUhlaWdodC1idG5JY29uX18xa3kzd3RxZjogMi40ZW0gIWRlZmF1bHQ7CiAgLS1mb250LWxpbmVIZWlnaHQtZGVmYXVsdF9fMWt5M3d0cWc6IDEuMzVlbSAhZGVmYXVsdDsKICAtLWZvbnQtbGluZUhlaWdodC1sZ19fMWt5M3d0cWg6IDU0cHggIWRlZmF1bHQ7CiAgLS1jb2xvci1kZWZhdWx0Q29sb3JfXzFreTN3dHFpOiAjODg4ODg4ICFkZWZhdWx0OwogIC0tY29sb3ItZGVmYXVsdFN0YXRlc0NvbG9yX18xa3kzd3RxajogbGlnaHRlbigjODg4ODg4ICFkZWZhdWx0LCA2JSkgIWRlZmF1bHQ7CiAgLS1jb2xvci1kZWZhdWx0Q29sb3JPcGFjaXR5X18xa3kzd3RxazogcmdiYSgxODIsIDE4MiwgMTgyLCAuNikgIWRlZmF1bHQ7CiAgLS1iZ0NvbG9yLXdoaXRlX18xa3kzd3RxbDogI0ZGRkZGRiAhZGVmYXVsdDsKICAtLWJnQ29sb3Itb3JhbmdlX18xa3kzd3RxbTogI2U5NWUzOCAhZGVmYXVsdDsKICAtLWJnQ29sb3Itc21va2VfXzFreTN3dHFuOiAjRjVGNUY1ICFkZWZhdWx0OwogIC0tYmdDb2xvci1ibGFja19fMWt5M3d0cW86IHJnYmEoMzAsMzAsMzAsLjk3KSAhZGVmYXVsdDsKICAtLWJnQ29sb3ItdHJhbnNwYXJlbnRfXzFreTN3dHFwOiB0cmFuc3BhcmVudCAhZGVmYXVsdDsKICAtLWJnQ29sb3ItZGFya0JhY2tncm91bmRfXzFreTN3dHFxOiAjNTU1NTU1ICFkZWZhdWx0OwogIC0tYm9yZGVyLW5vbmVfXzFreTN3dHFyOiAwICFkZWZhdWx0OwogIC0tYm9yZGVyLWRlZmF1bHRfXzFreTN3dHFzOiAxcHggc29saWQgIWRlZmF1bHQ7CiAgLS1ib3JkZXItdGhpbl9fMWt5M3d0cXQ6IDFweCAhZGVmYXVsdDsKICAtLWJvcmRlci10aGlja19fMWt5M3d0cXU6IDJweCAhZGVmYXVsdDsKICAtLWJvcmRlci1yYWRpdXNFeHRyYVNtYWxsX18xa3kzd3RxdjogMC4xMjVyZW0hZGVmYXVsdDsKICAtLWJvcmRlci1yYWRpdXNTbWFsbF9fMWt5M3d0cXc6IDAuMTg3NXJlbSAhZGVmYXVsdDsKICAtLWJvcmRlci1yYWRpdXNMYXJnZV9fMWt5M3d0cXg6IDAuMjVyZW0gIWRlZmF1bHQ7CiAgLS1ib3JkZXItcmFkaXVzRXh0cmVtZV9fMWt5M3d0cXk6IDAuODc1cmVtIWRlZmF1bHQ7CiAgLS1wYWRkaW5nLWJ0blZlcnRpY2FsX18xa3kzd3RxejogMTFweCAhZGVmYXVsdDsKICAtLXBhZGRpbmctYnRuSG9yaXpvbnRhbF9fMWt5M3d0cTEwOiAyMnB4ICFkZWZhdWx0OwogIC0tcGFkZGluZy1sYXJnZVZlcnRpY2FsX18xa3kzd3RxMTE6IDE1cHggIWRlZmF1bHQ7CiAgLS1wYWRkaW5nLWxhcmdlSG9yaXpvbnRhbF9fMWt5M3d0cTEyOiA0OHB4ICFkZWZhdWx0OwogIC0tcGFkZGluZy1zbWFsbFZlcnRpY2FsX18xa3kzd3RxMTM6IDVweCAhZGVmYXVsdDsKICAtLXBhZGRpbmctc21hbGxIb3Jpem9udGFsX18xa3kzd3RxMTQ6IDE1cHggIWRlZmF1bHQ7Cn0="}!./node_modules/@vanilla-extract/webpack-plugin/extracted/dist/vanilla-extract-webpack-plugin-extracted.cjs.js)
TypeError: this.getOptions is not a function`

### Link to reproduction

[https://github.com/tawhidurrahman/vet](url)

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Memory: 1.78 GB / 7.88 GB
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @vanilla-extract/css: ^1.2.3 => 1.2.3
    @vanilla-extract/webpack-plugin: ^1.1.0 => 1.1.0
```

**Comment by mattcompiles** [comment]
This error is coming from mini-css-extract-plugin not vanilla-extract. You are using webpack 4 with mini-css-extract-plugin v2 which only works with webpack 5.
