### ISSUE TITLE
Importing `.css.ts` files from other packages in a monorepo doesn't work with Webpack plugin

### ISSUE THREAD

**Issue by sambowler** [seek-oss/vanilla-extract#298]
### Describe the bug

When using npm workspaces importing a `.css.ts` file from a package other than the one currently being built causes the following error to be returned (based on the folder structure in the reproduction repo below):

```
ERROR in ../shared/index.css.ts
Module build failed (from ../../node_modules/@vanilla-extract/webpack-plugin/loader/dist/vanilla-extract-webpack-plugin-loader.cjs.js):
Error: Styles were unable to be assigned to a file. This is generally caused by one of the following:

- You may have created styles outside of a '.css.ts' context
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/setup
    at Object.getFileScope ([path]/node_modules/@vanilla-extract/css/fileScope/dist/vanilla-extract-css-fileScope.cjs.dev.js:31:11)
    at generateIdentifier ([path]/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js:121:49)
    at style ([path]/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js:270:21)
    at eval (webpack://webpack-test/../shared/index.css.ts?:8:79)
    at Object.../shared/index.css.ts ([path]/packages/shared/index.css.ts:19:1)
    at __webpack_require__ ([path]/packages/shared/index.css.ts:53:41)
    at [path]/packages/shared/index.css.ts:105:37
    at [path]/packages/shared/index.css.ts:108:12
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)
 @ ./index.ts 4:0-29
```

Importing the exact same file from the local package works as expected.

I tried chasing the issue through the code and could observe that [`setFileScope`](https://github.com/seek-oss/vanilla-extract/blob/master/packages/css/src/fileScope.ts#L9) never seemed to be called but that was as far as I could get with my limited Babel knowledge.

My scenario for wanting to do this is to have a design system (distributed as a package) as one workspace and a separate workspace for a site to document it.

```
repo
    packages
        design-system
            // .css.ts files distributed as a package
        docs
            // next.js documentation site consuming above design system
```

### Link to reproduction

[Repo →](https://github.com/sambowler/vanilla-extract-webpack-plugin-bug)

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 70.59 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.7.0 - ~/.nvm/versions/node/v16.7.0/bin/node
    npm: 7.20.3 - ~/.nvm/versions/node/v16.7.0/bin/npm
  Browsers:
    Chrome: 92.0.4515.159
    Chrome Canary: 95.0.4612.0
    Edge: 89.0.774.57
    Firefox: 91.0
    Safari: 14.1.1
    Safari Technology Preview: 14.2
```

**Comment by mattcompiles** [comment]
Your babel options are not being applied to the file. Changing the webpack.config.js TS rule to the following fixes the issue for me. 
```js
 {
   test: /\.ts$/,
   use: {
     loader: 'babel-loader',
     options: {
       presets: ['@babel/preset-typescript'],
       plugins: ['@vanilla-extract/babel-plugin'],
     },
   },
},
```

**Comment by sambowler** [comment]
Thanks for the quick reply @mattcompiles, really appreciated. Sorry, it looks like I missed that config in trying to boil down the exact problem.

The docs site I mentioned is actually a Next.js site, set up with the config in [the discussion around usage with Next](https://github.com/seek-oss/vanilla-extract/discussions/89#discussioncomment-1037361). Next's logs show that the custom .babelrc is correctly being picked up but the issue still appears to occur. I've updated the [example repo](https://github.com/sambowler/vanilla-extract-webpack-plugin-bug) to include Next now, apologies for the confusion.

**Comment by sambowler** [comment]
For anyone following along with this, I was able to resolve the issue by transpiling the modules from elsewhere in the monorepo using [`next-transpile-modules`](https://github.com/martpie/next-transpile-modules) and ensuring I was importing from the package (`import { thing } from 'my-package';`) instead of using a relative path (`import { thing } from '../packages/my-package';`)
