### ISSUE TITLE
Usage with other bundlers

### ISSUE THREAD

**Issue by Markcial** [seek-oss/vanilla-extract#3]
Hi, I am excited about having a new CSS in Js library with zero runtime cost.

Does this library can be used with other bundlers or is it only webpack specific?

I would like to be able to run it on a more minimal project with esbuild for example.

Not something that can hold me back to try it, I can still try it with webpack, but I am opening a low priority issue just to let you know

Thanks for your effort, appreciate it

**Comment by ssw1ss** [comment]
Interested in this as well. I'd like to use vanilla-extract with SvelteKit which uses Vite. As Markcial mentioned above, I'll still try it out regardless but it'd be neat to be able to use this with other bundlers.

**Comment by sami616** [comment]
Interested in using this with rollup!

**Comment by markdalgleish** [comment]
Nothing concrete at this point, but we're definitely interested in support for other bundlers.

**Comment by markdalgleish** [comment]
Check this out — @mattcompiles managed to get vanilla-extract working with esbuild: https://twitter.com/mattcompiles/status/1376748835947511812

**Comment by markdalgleish** [comment]
We have an open PR adding esbuild support, should hopefully land soon: https://github.com/seek-oss/vanilla-extract/pull/14

**Comment by markdalgleish** [comment]
I'm making good progress on a Rollup integration too: https://twitter.com/markdalgleish/status/1378898886819913731

**Comment by markdalgleish** [comment]
Just shipped the esbuild plugin: https://github.com/seek-oss/vanilla-extract#esbuild

**Comment by zoontek** [comment]
Does someone has a successful config with `vite` + `@vanilla-extract/esbuild-plugin`?

I tried:

```ts
export default defineConfig({
  plugins: [preact(), vanillaExtractPlugin({ projectRoot: path.resolve(__dirname) })],
});
```

Without success:

> Error: New styles cannot be registered dynamically after initial boot. This is to ensure that styles are statically extractible.

**Comment by mattcompiles** [comment]
@zoontek Will be looking into vite at some point soon hopefully. However, isn't rollup the primary bundler for vite? I thought esbuild was only used as a babel replacement?

**Comment by zoontek** [comment]
Ah, maybe! I just tried it without knowing much about it.

**Comment by Markcial** [comment]
I can confirm that the esbuild plugin works perfectly, just tested it right now. Congratulations 👏

**Comment by codepunkt** [comment]
Also interested in using this with rollup/vite - might use it in @wilsonjs.

**Comment by mattcompiles** [comment]
Hopefully have something to show with vite very soon.

**Comment by markdalgleish** [comment]
Just an update on the Rollup integration work—since it doesn’t have first class CSS bundling support, we're thinking it’s probably not a good target for static extraction.
