### ISSUE TITLE
Importing `.css.ts` files from other packages in a monorepo with Vite plugin

### ISSUE THREAD

**Issue by samrose3** [seek-oss/vanilla-extract#320]
### Describe the bug

I've been testing out a vanilla-extract based component library (following patterns from Braid) along side a test `site` in a monorepo.

When trying to build the component package from source within the site via Vite, the virtual files aren't being resolved properly (getting a `404`)

I am not sure if this is an issue with either Vite, my [setup/config](https://github.com/samrose3/pixels/blob/main/site/vite.config.ts), or the vanilla-extract plugin (possibly [here at resolveId](https://github.com/seek-oss/vanilla-extract/blob/master/packages/vite-plugin/src/index.ts#L33)).

### Link to reproduction

Examples repo 👉  [@samrose3/pixels](https://github.com/samrose3/pixels) (`yarn && yarn dev`)

Example [codesandbox](https://codesandbox.io/s/charming-water-0gxdr?file=/site/vite.config.ts) with slight `vite.config.ts` modifications from above repo setup.

<img width="1219" alt="Screen Shot 2021-08-25 at 8 09 19 AM" src="https://user-images.githubusercontent.com/11774595/130795490-11fe9347-9ca4-4d9f-86eb-9deae5cf245d.png">

Just a note, I have been able to achieve a similar monorepo cross-package compile using the Webpack plugin. That seems to work well as expected. Only Vite has been giving me trouble.

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 11.5.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 1.92 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Browsers:
    Chrome: 92.0.4515.159
    Chrome Canary: 95.0.4621.0
    Firefox Nightly: 93.0a1
    Safari: 14.1.2
  npmPackages:
    @vanilla-extract/vite-plugin: ^1.1.1 => 1.1.1 
    vite: ^2.4.4 => 2.4.4 
    webpack: ^5.50.0 => 5.50.0 
```

**Comment by samrose3** [comment]
I also wanted to test if the vanilla-extract Vite plugin would compile Braid from the node_modules folder. Not getting a `404` here, but am still missing something that is causing it to fail when processing the `braid-design-system` modules.

💻 [CodeSandbox Braid + Vite example](https://codesandbox.io/s/my-vite-app-84rnh?file=/src/App.tsx)

<img width="812" alt="Screen Shot 2021-08-25 at 10 59 30 AM" src="https://user-images.githubusercontent.com/11774595/130816769-7c2bc1e1-f4aa-4a42-a57f-cbca957c7720.png">

My primary goal is to understand how to ship and build from source using vanilla-extract and Vite.

**Comment by sambowler** [comment]
@samrose3 Not sure if it'll be the same deal here but I was able to resolve a similar issue by transpiling the other packages in the monorepo (see https://github.com/seek-oss/vanilla-extract/issues/298). I don't know how to achieve that kind of thing with Vite but it might at least give you an avenue to explore.

**Comment by samrose3** [comment]
@sambowler right, I have had success with transpiling the packages prior to using in another package. Ideally, I'd like to deliver source assets uncompiled to the end consumer. When trying to publish and build `.css.ts` from the `node_modules` folder, I run into a similar problem.

Thank you for the suggestion!

Question regarding importing your compiled styles... are you importing the `dist/style.css` file once in you application? I find this approach straightforward, but you lose the ability to tree-shake or remove unused styles.

**Comment by alex-page** [comment]
We are also seeing an issue with `load-fallback`

```
[load-fallback] Could not load @polaris/components/src/atoms/atoms.css.ts.vanilla.css?hash=11ada95915bb4f9f356fcb61b6677f5c (imported by src/atoms/atoms.css.ts): ENOENT: no such file or directory, open '@polaris/components/src/atoms/atoms.css.ts.vanilla.css'
```

I assume the hash is changing and vite is not picking up the new value. The flow we have right now is change `@polaris/components` this causes the vite plugin to refresh. No changes come through and we see this error.

**Comment by mattcompiles** [comment]
Hey 👋,

Sorry it took me a bit to have a look at this. I think there's a few different issues being raised here so it would be good to separate them out into separate issues. However, the initially raised issues here seems to be fixed by upgrading to the latest `@vanilla-extract/vite-plugin` and `vite` packages.

**Comment by samrose3** [comment]
> the initially raised issues here seems to be fixed by upgrading to the latest `@vanilla-extract/vite-plugin` and `vite` packages.

Can confirm 👍 upgrading to `^2.0.1` did the trick in resolving the imports across monorepo pacakges

I think we can close this issue, but it would be good to document the `load-fallback` in a separate issue. That error may be due to how we are building packages with vite + vanilla-extract in watch mode while also running a separate app using the dev server concurrently.

**Comment by mattcompiles** [comment]
@samrose3 awesome. Going to close this issue. Feel free to make another one with the repro for the other problem.

**Comment by Tatamethues** [comment]
I think I'm facing the same problem. `button.css.ts:1 GET http://localhost:3000/@id/packages/future-ui/src/Button/button.css.ts$$$dashboard.vanilla.js net::ERR_ABORTED 404 (Not Found)`.

the app is using turborepo with pnpm. All versions are latest.
app's viteconfig
```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react(),vanillaExtractPlugin()]
})
```
package.json
```
{
  "dependencies": {
    "@blade/future-ui": "workspace:*",
    "@vanilla-extract/css": "^1.6.8",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
  },
  "devDependencies": {
    "@blade/eslint-config": "workspace:*",
    "@types/react": "^17.0.33",
    "@types/react-dom": "^17.0.10",
    "@vanilla-extract/vite-plugin": "^3.1.2",
    "@vitejs/plugin-react": "^1.0.7",
    "eslint": "^8.5.0",
    "tsconfig": "workspace:*",
    "typescript": "^4.4.4",
    "vite": "^2.7.2"
  }
}
