### ISSUE TITLE
Vanilla extract webpack issue with sass loader also

### ISSUE THREAD

**Issue by claidler** [seek-oss/vanilla-extract#340]
### Describe the bug
I've been trying for many hours to get vanilla-extract working with my existing sass/css-modules project webpack config by following the guides online, but I am getting an error and am wondering if you guys could help me please? I'm not sure if it's a bug or something I'm doing wrong. Quite possibly me! 

### Config and Errors

Please see my errors below and let me know if there's anything else you need. Many thanks.

![Screenshot from 2021-09-06 08-44-48](https://user-images.githubusercontent.com/43636691/132179953-5f795a1a-024b-4963-abea-a7790bdb0cf4.png)
![Screenshot from 2021-09-06 08-45-31](https://user-images.githubusercontent.com/43636691/132179965-1c2ae297-2d74-4d8f-aa80-f0318100ec5a.png)

**Comment by claidler** [comment]
I think this may be related to the fact that I'm using a shared package in a monorepo via a local dependency. Something like:

hs-shared: "file: ../hs-shared"

**Comment by claidler** [comment]
I'm going to close this as I'm pretty sure it's a config issue my end related complexity with monorepos

**Comment by mattcompiles** [comment]
@claidler It looks like your scss rules are applying to vanilla.css files. Try adding an `exclude: [/\.vanilla\.css$/i]` to your scss rules.

**Comment by claidler** [comment]
Thanks for the response @mattcompiles , makes sense, and I'm sure that is the problem, but no luck! I'm reassessing my monorepo setup
