### ISSUE TITLE
Seeing: 'Styles were unable to be assigned to a file...' runtime error on any Gatsby project.

### ISSUE THREAD

**Issue by SladtheLad** [seek-oss/vanilla-extract#347]
### Describe the bug
Hello! I've really enjoyed using this in a Typescript app I've been working on and I decided to try it out on a Gatsby project. I followed the instructions to the letter, but I am seeing runtime errors whenever trying to apply a style. I decided to see if a fresh Gatsby starter had this issue, and it does. The error seems to be the generic run time error:

```
There was an error while trying to create the client-only shell for displaying SSR errors:
        Styles were unable to be assigned to a file. This is generally caused by one of the following:

- You may have created styles outside of a '.css.ts' context
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/setup
```

### Link to reproduction
Here's a reproduction I hosted on [CodeSandbox](https://codesandbox.io/s/intelligent-bouman-xqqru). If you navigate to the port 8000 pane when it prompts you, you will see the error.

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 11.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 417.32 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 93.0.4577.63
    Safari: 14.1.2
  npmPackages:
    @vanilla-extract/css: ^1.4.1 => 1.4.1 
```

**Comment by danielberndt** [comment]
seems like your using the `@vanilla-extract/babel-plugin` instead of the `gatsby-plugin-vanilla-extract` plugin within the `gatsby-config.js`

**Comment by danielberndt** [comment]
ah I think I see how you've got confused! The Gatsby section is so short that it looks like the section below still belongs to it:

![image](https://user-images.githubusercontent.com/856386/132857314-527e175d-0ebe-4e5b-8362-67fcc00b986b.png)

**Comment by SladtheLad** [comment]
That does indeed fix it, in both environments! Thank you! Maybe an update to these docs? 😆
