### ISSUE TITLE
[Vite]: Generated CSS variables are not defined 

### ISSUE THREAD

**Issue by nialldbarber** [seek-oss/vanilla-extract#351]
### Bug info
Apologies if I'm misunderstanding something here, but I can't access variables set in `createTheme`, inside a `style` block. This might just be a Vite problem but the generated css variables are not defined. 

![variables not defined](https://res.cloudinary.com/doxyfmuxf/image/upload/v1631298269/niall/Screenshot_2021-09-10_at_19.06.56_qnd2mi.png)

### Link to relevant files
[Repo](https://github.com/nialldbarber/vite-vanilla-extract)
[Style set up](https://github.com/nialldbarber/vite-vanilla-extract/blob/main/src/Button/button.css.ts)
[Implementation of styles](https://github.com/nialldbarber/vite-vanilla-extract/blob/main/src/Button/button.tsx)

### System Info
```bash
  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 550.46 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome Canary: 95.0.4638.0
    Firefox: 83.0
    Firefox Developer Edition: 92.0
    Firefox Nightly: 80.0a1
    Safari: 14.1.1
  npmPackages:
    @vanilla-extract/css: ^1.5.0 => 1.5.0 
    @vanilla-extract/vite-plugin: ^2.0.2 => 2.0.2 
    vite: ^2.5.4 => 2.5.6 
```

```node

```

**Comment by mattcompiles** [comment]
Hey bud 👋

The createTheme function returns a class name that assigns the variables. I can see you're not assigning it anywhere in your document though. 

If you want a default theme that's assigned by default you can use `createGlobalTheme(':root', ...)`
