### ISSUE TITLE
::after content style not being applied

### ISSUE THREAD

**Issue by claidler** [seek-oss/vanilla-extract#353]
```
export const addButton = style({
	margin: "25px 0",
	position: "relative",
	height: 0,
	display: "block",
	width: 16,
	borderBottom: `2px solid ${hsTheme.colors.white}`,
	"::after": {
		content: "",
		display: "block",
		transform: "rotate(90deg)",
		height: 0,
		width: 16,
		borderBottom: `2px solid ${hsTheme.colors.white}`,
	},
})
```

Hi the first part is being applied, but the `::after` is not. Any idea what is going wrong here?
It works in my SCSS file that I'm moving it from:

```
.addButton {
  margin: 25px 0;
  position: relative;
  height: 0;
  display: block;
  width: 16px;
  border-bottom: 2px solid $white;
  transform: rotate(0deg);
}

.addButton::after {
  content: '';
  display: block;
  transform: rotate(90deg);
  height: 0;
  width: 16px;
  border-bottom: 2px solid $white;
}
```

**Comment by markdalgleish** [comment]
It's a bit of a gotcha, but `content: ""` should be `content: '""'` (as in, empty quotes _inside_ the string) because you're embedding the CSS value `""` in a JS string.

**Comment by claidler** [comment]
> It's a bit of a gotcha, but `content: ""` should be `content: '""'` (as in, empty quotes _inside_ the string) because you're embedding the CSS value `""` in a JS string.

Ahh 🤦🏻‍♂️ thank you!
