### ISSUE TITLE
Using short/debug identifiers outside of webpack

### ISSUE THREAD

**Issue by iiroj** [seek-oss/vanilla-extract#372]
### Describe the bug
When using the webpack and babel plugin, I can configure `identifiers: isProduction ? 'short' : 'debug'` to control how the class names are generated inside webpack (or "client-side").

However, when doing SSR (code goes only through babel, not webpack, so "server-side"), the same cannot be configured, and it seems the generated class names are always of the type 'debug'.

It would be convenient if the babel plugin also contained the `identifiers` option, just like the webpack plugin:

```json
{
  "plugins": [
    ["@vanilla-extract/babel-plugin", { "identifiers": "short" }]
  ] 
}
```

### Link to reproduction
1. git clone https://github.com/iiroj/iiro.fi
1. run `npm ci`
1. run `npm run --workspace=site build`
1. notice how `site/dist/index.html` contains debug class names, as well as all CSS files
1. change the webpack plugin config at `site/webpack.config.babel.ts` to generate `short` identifiers and re-build
1. notice how the index.html file still contains debug class names

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 260.52 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.1 - /opt/homebrew/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 7.24.0 - /opt/homebrew/bin/npm
  Browsers:
    Firefox: 92.0
    Safari: 14.1.2

```

**Comment by iiroj** [comment]
I investigated how to configure this behavior, and something like this would work.

In the plugin's visitor Program's `exit` stage, adding into this conditional the following code to configure the current adapter:

```diff
      Program: {
        exit(path) {
          if (this.isCssFile && !this.alreadyCompiled) {
// Set adapter's identOption from babel config
if ('identifier' in opts) {
  var ident = ['short', 'debug'].includes(opts.identifier) ? opts.identifier : 'debug'
  var adapter = require('@vanilla-extract/css/adapter');
  var thisAdapter = Object.assign(adapter.mockAdapter, { getIdentOption: () => ident })
  adapter.setAdapter(thisAdapter)
            }
            // Wrap module with file scope calls
            const buildSetFileScope = this.isESM
              ? buildSetFileScopeESM
              : buildSetFileScopeCJS;
            path.unshiftContainer(
              'body',
              buildSetFileScope({
                filePath: t.stringLiteral(this.filePath),
                packageName: t.stringLiteral(this.packageName),
              }),
            );

            path.pushContainer('body', buildEndFileScope());
          }
        },
      },
```

https://github.com/seek-oss/vanilla-extract/blob/0ac48dd20a1c34d110932cb8c9fd58d181a30bd5/packages/babel-plugin/src/index.ts#L182-L200

**Comment by mattcompiles** [comment]
The babel-plugin should be environment agnostic so I don't think this makes sense to live there. 

If you don't run your code through a bundler the identifiers are controlled by `process.env.NODE_ENV`, where `production` will result in `short` identifiers. Can you try setting `NODE_ENV=production` for your builds and see if that fixes the clashing identifiers?

**Comment by iiroj** [comment]
Hello @mattcompiles, thanks for the reply. Setting `NODE_ENV` to different values does not seem to affect my output, and I am already using it as `NODE_ENV=production` in my build script.

The way I've interpreted is, that `@vanilla-extract/css` sets the "browser runtime adapter" with this behavior only if there is a `window`, which there won't be during SSR:

https://github.com/seek-oss/vanilla-extract/blob/0ac48dd20a1c34d110932cb8c9fd58d181a30bd5/packages/css/src/runtimeAdapter.ts#L74-L76

With some debugging I verified that the "mock adapter" is always used during SSR:

https://github.com/seek-oss/vanilla-extract/blob/0ac48dd20a1c34d110932cb8c9fd58d181a30bd5/packages/css/src/adapter.ts#L12

That always returns `debug` for the ident option:

https://github.com/seek-oss/vanilla-extract/blob/0ac48dd20a1c34d110932cb8c9fd58d181a30bd5/packages/css/src/adapter.ts#L9

And finally, this code is not used because the "mock adapter" always includes the ident option getter:

https://github.com/seek-oss/vanilla-extract/blob/0ac48dd20a1c34d110932cb8c9fd58d181a30bd5/packages/css/src/adapter.ts#L67-L70

**Comment by mattcompiles** [comment]
@iiroj You're right, thanks for looking into this. The intention is for that behaviour to be consistent and it seems it was missed for the mock adapter. We should update the mock adapter to check `NODE_ENV` as well.

**Comment by iiroj** [comment]
Thanks @mattcompiles! That PR fixes my issue, although it doesn't allow one to choose "debug" identifiers _and_ use `NODE_ENV=production` at the same time.

**Comment by mattcompiles** [comment]
@iiroj is that something you need?

**Comment by iiroj** [comment]
@mattcompiles personally, no, so this is fine. Just that the webpack plugin does allow this.
