### ISSUE TITLE
Webpack error

### ISSUE THREAD

**Issue by huijiewei** [seek-oss/vanilla-extract#40]
When i run webpack, i have some error.

Module parse failed: Unexpected token (4:7)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.

Project: https://github.com/huijiewei/react-agile-ui

**Comment by LekoArts** [comment]
When upgrading packages I'm also seeing a similar error:

![image](https://user-images.githubusercontent.com/16143594/115680193-a45b6c00-a353-11eb-9903-af46e9e60a7c.png)

Gatsby is also reporting this as a webpack error:

![image](https://user-images.githubusercontent.com/16143594/115680257-b3dab500-a353-11eb-82c3-d5bb32c58034.png)

I could try to bisect the package versions later this week.

**Comment by hactrz** [comment]
I have the same problem in my project. 
![image](https://user-images.githubusercontent.com/33606487/115695685-70943c80-a37b-11eb-9dae-c4dac5095320.png)
I tried to figure it out using the create-react-app example 
(https://github.com/hactrz/vanilla-extract-example), but got a new error:
![Screenshot from 2021-04-22 14-58-44](https://user-images.githubusercontent.com/33606487/115695559-59554f00-a37b-11eb-88b2-0327a78f0718.png)

**Comment by mattcompiles** [comment]
Thanks for the report. Fix should be out soon.

**Comment by mattcompiles** [comment]
@hactrz In your `vanilla-extract-example` you're adding the babel plugin on the wrong line so it's not being registered at all, hence the dynamic styles error. Swapping lines 423 & 424 might be enough to get you going. 

https://github.com/hactrz/vanilla-extract-example/blob/0f73188fbf53bfbb95fb387e38fb6f5b19733cca/config/webpack.config.js#L423
