### ISSUE TITLE
Strange Bundlephobia Results

### ISSUE THREAD

**Issue by knpwrs** [seek-oss/vanilla-extract#406]
Let me preface this by saying that It's entirely possible that I'm not properly understanding what "zero runtime" means in terms of this library.

When I run [`@vanilla-extract/css` through Bundlephobia](https://bundlephobia.com/package/@vanilla-extract/css@1.6.1) I see a result of 52.7kB (17.7kB gzipped), which doesn't quite seem like "zero runtime." Compare to running [`linaria` through Bundlephobia](https://bundlephobia.com/package/linaria@3.0.0-beta.13) where I can see a result of 467B (313B gzipped). This seems a lot closer to "zero runtime."

Does `@vanilla-extract/css` typically get tree-shaken out of bundles at build-time? Or am I misunderstanding what "zero runtime" means for this library?

**Comment by markdalgleish** [comment]
Anything imported within a `.css.ts` file doesn't end up in your final bundle since it's evaluated at build time, so tools like Bundlephobia are going to give you incorrect results.
