### ISSUE TITLE
vite-plugin 3.0.0 will not transfer style with postcss

### ISSUE THREAD

**Issue by Ttou** [seek-oss/vanilla-extract#434]
### Describe the bug

vite-plugin@3.0.0 has this issue, vite-plugin@2.1.3 not.

### Link to reproduction

https://codesandbox.io/s/cranky-mopsa-0ejeh

**Comment by Ttou** [comment]
fixed

**Comment by Ttou** [comment]
@benjervis upgrade vite to 2.7 cause same problem

**Comment by benjervis** [comment]
Hi @Ttou ,

Is it the exact same problem? I do get an error when running it with the new deps, but it seems vue related rather than vanilla. Do you have another codesandbox repro I could look at?

**Comment by Ttou** [comment]
@benjervis 

[vite 2.6.14](https://codesandbox.io/s/zealous-tharp-ujsgz)
[vite 2.7.2](https://codesandbox.io/s/gifted-panna-b0bo0)

**Comment by benjervis** [comment]
Looks like vite released some breaking changes in 2.7 that interfered with our plugin. `@vanilla-extract/vite-plugin@3.1.1` should fix this for you.

**Comment by Ttou** [comment]
@benjervis fixed
