### ISSUE TITLE
createThemeContract null values type error

### ISSUE THREAD

**Issue by KenanYusuf** [seek-oss/vanilla-extract#438]
### Describe the bug
Using theme variables that have been created using `createThemeContract` with their values set as `null` gives the following type error:
```
Type 'CSSVarFunction | MapLeafNodes<any, CSSVarFunction>' is not assignable to type 'CSSVarFunction | Color | Color[] | (CSSVarFunction | Color)[]'.
  Type 'MapLeafNodes<any, CSSVarFunction>' is not assignable to type 'CSSVarFunction | Color | Color[] | (CSSVarFunction | Color)[]'.
    Type 'MapLeafNodes<any, CSSVarFunction>' is not assignable to type '"currentcolor"'.
```

Example code:
```ts
export const colors = createThemeContract({
  red: null,
  blue: null,
  yellow: null
});

export const colorsClass = createTheme(colors, {
  red: "red",
  blue: "blue",
  yellow: "yellow"
});

globalStyle("body", {
  background: colors.blue
});
```

I am working around the issue currently by setting the values to empty strings e.g:

```ts
export const colors = createThemeContract({
  red: "",
  blue: "",
  yellow: ""
});
```

### Link to reproduction

https://codesandbox.io/s/elated-borg-4i12t?file=/styles/theme.css.ts

**Comment by markdalgleish** [comment]
I think this is happening because you're not in strict mode. Try adding `"strict": true,` to your tsconfig.

**Comment by KenanYusuf** [comment]
> I think this is happening because you're not in strict mode. Try adding `"strict": true,` to your tsconfig.

That fixes it, thanks 🎉
