### ISSUE TITLE
Nuxt 3 + Vanilla Extract Vite SSR error

### ISSUE THREAD

**Issue by tkofh** [seek-oss/vanilla-extract#445]
### Describe the bug
Using Nuxt 3 and the Vanilla Extract Vite plugin, there is a flash of unstyled content on load. When viewing source, it doesn't appear that `<style>` tags are being added to the server rendered markup.

This is not an issue when SSR is disabled in Nuxt.

### Link to reproduction

[Repo](https://github.com/tkofh/nuxt3-vanilla-extract-ssr-error) (Reused from #446, though I don't believe these issues to be related)

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 12.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 439.40 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 95.0.4638.54
    Firefox: 89.0.1
    Safari: 15.1
  npmPackages:
    @vanilla-extract/css: ^1.6.3 => 1.6.3 
    @vanilla-extract/vite-plugin: ^3.0.0 => 3.0.0 
```

**Comment by mattcompiles** [comment]
SSR of styles in Vite is an interesting one as styles aren't pulled into CSS files. I'm not sure how Nuxt handles this currently. How does it work for static CSS files?

**Comment by tkofh** [comment]
When defining [global css files in `nuxt.config.ts`](https://v3.nuxtjs.org/docs/directory-structure/nuxt.config#css), the server returns a `<link>` tag referencing the file. 

The client seems to immediately replace that with a `<style>` tag of the contents in dev mode. In production, the `<link>` tag is left alone.

**Comment by tkofh** [comment]
I've updated the example repo with a static css file, and upgraded all the deps. Still seeing the FOUC.
