### ISSUE TITLE
Question: Has anyone migrated from styled-components to vanilla-extract ?

### ISSUE THREAD

**Issue by christoffee** [seek-oss/vanilla-extract#467]
Sorry not sure if you are allowing questions on here... but just wanted to reach out to anyone using `vanilla-extract` that may have migrated from `styled-components`... if the were any tips or process used ?

**Comment by KenanYusuf** [comment]
You might have more luck asking on [discussions](https://github.com/seek-oss/vanilla-extract/discussions)!
