### ISSUE TITLE
Valid `transform` sprinkles values can create invalid class names

### ISSUE THREAD

**Issue by zgreen** [seek-oss/vanilla-extract#475]
### Describe the bug

Certain valid `transform` sprinkles values can create invalid class names. Looks to me like characters like `(`, `)`, and `%` may not be getting escaped as they should be.

STR:
```ts
import { defineProperties, createSprinkles } from "@vanilla-extract/sprinkles";

const properties = defineProperties({
  properties: {
    transform: ["translateY(-50%)"]
  }
});

const sprinkles = createSprinkles(properties);

export const bugExample = sprinkles({ transform: "translateY(-50%)" }); // will generate a broken class name
```

My current workaround is to just not use sprinkles for values like that.

Also worth noting: weirdly, this bug caused another issue which was really tricky to debug: all of my `selector` styles became invalid (they all generated an extra `.` in the CSS, like `..example { color: red; }`).

### Link to reproduction

Here: https://codesandbox.io/s/elegant-darwin-6e1ps?file=/src/App.css.ts:344-378
Note that the `transform` style is not applied as expected, and that the generated class name looks like this: `sprinkles_transform_translateY(-50%)_mobile__1qjyzon73` (which is invalid).

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 11.6
    CPU: (8) arm64 Apple M1
    Memory: 166.69 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    npm: 8.1.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 95.1.31.88
    Chrome: 95.0.4638.69
    Chrome Canary: 98.0.4708.0
    Firefox: 93.0
    Firefox Developer Edition: 95.0
    Safari: 15.0
  npmPackages:
    @vanilla-extract/css: ^1.6.2 => 1.6.3
    @vanilla-extract/sprinkles: ^1.3.0 => 1.3.1
```
Thanks again for the library, I'm really liking it. Happy to help w/ a PR if you want. Cheers :)

**Comment by mattcompiles** [comment]
Thanks for the repro. In the meantime you can work around the issue by giving the transform a different alias. 

e.g. 
```js
const properties = defineProperties({
  properties: {
	transform: { "up50%": "translateY(-50%)" }
  }
});

```
