### ISSUE TITLE
@vanilla-extract/next-plugin produces non-ES5 compatible output

### ISSUE THREAD

**Issue by Dremora** [seek-oss/vanilla-extract#507]
### Describe the bug
When using `@vanilla-extract/recipes` or `@vanilla-extract/sprinkles` alongside `@vanilla-extract/next-plugin`, the output produced during the Next.js build has non-ES5 compatible syntax. Namely, it's the `const` keyword, object spreading, arrow functions, and possibly more.

Likely related to #214.

### Link to reproduction

Steps:
- Open [Codesandbox](https://codesandbox.io/s/vanilla-extract-next-js-forked-w75tm)
  - this is a minimal Next.js app, there are two files of interest here - `src/pages/index.tsx `and `src/styles.css.ts`
- Once the container starts up, open a new terminal tab
- Run the following commands:
  - `yarn build`
  - `cd .next/static/chunks/pages`
  - `cat index-*`
- You will see a small file printed. When unminified, it'll contain a segments like this one:

```javascript
const s = (n, t) => {
  for (const a of Object.keys(n)) if (n[a] !== t[a]) return !1;
  return !0;
};
```

and this one:

```javascript
(n) => {
  let t = e.defaultClassName;
  const a = { ...e.defaultVariants, ...n };
  for (const s in a) {
    var r;
    const n =
      null !== (r = a[s]) && void 0 !== r ? r : e.defaultVariants[s];
    if (null != n) {
      let a = n;
      "boolean" === typeof a && (a = !0 === a ? "true" : "false"),
        (t += " " + e.variantClassNames[s][a]);
    }
  }
  for (const [o, u] of e.compoundVariants) s(o, a) && (t += " " + u);
  return t;
});
``` 

### System Info

```node
  System:
    OS: macOS 11.5.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 492.42 MB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.asdf/installs/nodejs/16.13.0/bin/node
    Yarn: 1.22.15 - ~/.asdf/shims/yarn
    npm: 8.1.0 - ~/.asdf/installs/nodejs/16.13.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox Developer Edition: 94.0
    Safari: 14.1.2

```

**Comment by mattcompiles** [comment]
Thanks for raising this. Historically we've targeted node for transpilation as most vanilla-extract code runs at build time. However this is not the case for things like Sprinkles and Recipes. We can address this but we'll need to draw the line somewhere. Not sure transpiling all the way back to es5 is necessary. If you need to support IE I think that shouldn't be on us.
