### ISSUE TITLE
Vanilla Should Preserve HSL Color Format When Creating Theme

### ISSUE THREAD

**Issue by phil-lgr** [seek-oss/vanilla-extract#518]
### Describe the bug

Color values are passed in hsl() format, but vanilla outputs colors in hex format.

I expect my color primary 500 to be:

`  --colors-primary-500__ucbyqq4: hsl(222deg 50% 50% / 100%)`

But I get:

`  --colors-primary-500__ucbyqq4: #4066bf;`

![image](https://user-images.githubusercontent.com/9644867/144329766-d7deb554-209c-4951-bad1-d057efd7ed2a.png)

### Link to reproduction

Let me know if needed.

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 11.6.1
    CPU: (8) arm64 Apple M1
    Memory: 68.59 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.11 - /opt/homebrew/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Brave Browser: 96.1.32.113
    Chrome: 96.0.4664.55
    Safari: 15.1
  npmPackages:
    @vanilla-extract/css: ^1.6.3 => 1.6.3 
    @vanilla-extract/webpack-plugin: ^2.1.0 => 2.1.0 
    webpack: 5.64.1 => 5.64.1 
```

**Comment by phil-lgr** [comment]
I'm trying to follow here: https://github.com/seek-oss/vanilla-extract/blob/1e49dfc4fc21ccb53870e297e5e4664b098cc22e/packages/css/src/vars.ts#L65 but I can't see vanilla doing something with passed string, it just run the values through `String(value)` 🤔

**Comment by mattcompiles** [comment]
Pretty sure this issue is unrelated to vanilla-extract. We don't really do any post-processing of your CSS. Without a repro I would guess something in your pipeline is causing this to occur. Maybe CSS minification?

**Comment by phil-lgr** [comment]
@mattcompiles, I agree, there is no CSS transformation happening as far as I can see... I just tried:

```ts
createGlobalTheme(':root', {
  myColor: 'hsl(100, 100%, 50%)',
  myColorhsl: 'hsl(222 50% 50%)',
});
```

And I still get hex on the output. It's prob postcss that is doing something. Thanks for the quick reply!
