### ISSUE TITLE
Type error: use Omit or Pick with RecipeVariants<X>

### ISSUE THREAD

**Issue by huijiewei** [seek-oss/vanilla-extract#527]
### Describe the bug
I export type use RecipeVariants, other file use Omit or Pick with this type. webstorm or vscode get type error

### Link to reproduction
RecipeVariants type
https://github.com/huijiewei/agile-ui/blob/main/packages/react/src/button/Button.css.ts

use Omit or Pick
https://github.com/huijiewei/agile-ui/blob/main/packages/react/src/button/ButtonGroup.tsx

### Some info
After my test， if ts compilerOptions strict set true, type is error

more detail config is strictNullChecks

### System Info

```node
 System:
    OS: macOS 12.0.1
    CPU: (6) x64 Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
    Memory: 294.38 MB / 16.00 GB
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 17.2.0 - /usr/local/bin/node
    npm: 8.1.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 96.0.4664.93
    Safari: 15.1
  npmPackages:
    esbuild: ^0.14.3 => 0.14.3 
```

**Comment by huijiewei** [comment]
https://codesandbox.io/s/vademo-z4ss9?file=/src/components/ButtonGroup.tsx

I use codesandbox write a demo . that is ok.

**Comment by huijiewei** [comment]
After my test， if ts compilerOptions strict set true, type is error

**Comment by graup** [comment]
`RecipeVariants` includes `undefined`, so `keyof RecipeVariants` returns `never`. To use `Omit`, you have to ignore `undefined`, for example using `NonNullable`:

```ts
type Variants = RecipeVariants<typeof recipe>;
type Props = Omit<React.ComponentProps<'button'>, keyof NonNullable<Variants>> & Variants;
```

**Comment by mattcompiles** [comment]
Closing as @graup's response is correct.

**Comment by ayoubqrt** [comment]
hi,

better to have this type imo : 
`type Variants = NonNullable<RecipeVariants<typeof button>>;`

**Comment by emlai** [comment]
Why does `RecipeVariants` include `undefined`? We ended up adding `NonNullable` to all of our usages of `RecipeVariants`. I feel `RecipeVariants` shouldn't include `undefined` in the first place. Or is there a good reason for it?

**Comment by mike-wheel** [comment]
> Why does `RecipeVariants` include `undefined`? We ended up adding `NonNullable` to all of our usages of `RecipeVariants`. I feel `RecipeVariants` shouldn't include `undefined` in the first place. Or is there a good reason for it?

Bumping this question, I'm curious about this too!

**Comment by askoufis** [comment]
> > Why does `RecipeVariants` include `undefined`? We ended up adding `NonNullable` to all of our usages of `RecipeVariants`. I feel `RecipeVariants` shouldn't include `undefined` in the first place. Or is there a good reason for it?
> 
> Bumping @emlai's question, I'm curious about this too!

This is because [`RecipeVariants`](https://github.com/vanilla-extract-css/vanilla-extract/blob/ccb4957b549107394cd6867da71b3e979c96a28d/packages/recipes/src/types.ts#L56) is just getting the type of [the first parameter of the input recipe function, which is optional](https://github.com/vanilla-extract-css/vanilla-extract/blob/ccb4957b549107394cd6867da71b3e979c96a28d/packages/recipes/src/types.ts#L49). It's optional because you may want to use only the default variants, in which case you don't need to pass in anything.

I agree that it probably makes more sense to include the `NonNullable` within `RecipeVariants` as it's likely most users want to access the properties and don't actually care about the optionality of the parameter.

**Comment by mike-wheel** [comment]
Yeah!  These are the workarounds that I've seen:

```tsx
type ButtonSize = NonNullable<
  NonNullable<RecipeVariants<typeof buttonRecipe>>['size']
>;

// Resolves to:
//   type ButtonSize = "mini" | "small" | "large"
```
or 
```tsx
type ButtonSize = Required<
  NonNullable<RecipeVariants<typeof buttonRecipe>>
>['size'];
```

Neither are very easy to read/understand and they're so long `prettier` is wrapping them 😬.  It would be nice if either of these was abstracted into a type utility!  I'm imagining something like this:
```tsx
const ButtonSize = RecipeVariant<typeof buttonRecipe, "size">;
```
