### ISSUE TITLE
TS complains when !important is used

### ISSUE THREAD

**Issue by sami616** [seek-oss/vanilla-extract#541]
This doesn't seem to affect properties that accept more generic values (ie: margin) but others that accept a union complain.

Ie: position: 'static !important'

Could any clever trickery with TS template literals be put at use here to accept values appended with '!important' ?

**Comment by mattcompiles** [comment]
We use `csstype` for typing all the CSS properties. I believe this is a trade-off made by that library. This isn't something we'd fix in vanilla-extract directly. 

Relevant issue: https://github.com/frenic/csstype/issues/114
