### ISSUE TITLE
Vite React, Jest and Vanilla CSS setup

### ISSUE THREAD

**Issue by kishek2000** [seek-oss/vanilla-extract#557]
### Describe the bug
Hey there! Been struggling with a bug recently with a vite project in react, where I'm using vanilla extract for our design system. In the process of integrating jest unit tests, I get the same error every time as provided in the dump below. I've got it working successfully with babel, but we want to run our tests with esbuild and can't seem to find a way of getting it to work.

Just wondering if there's any suggestions on how to make the testing work with esbuild. Thanks!

### Link to reproduction
I've made a very basic reproduction of the bug in this repo here where vanilla, vite, jest are used and a basic test is being run. I've cleaned the testing of any config and just use ts-jest, avoiding babel-jest because we want to use esbuild as mentioned above.

https://github.com/kishek2000/vite-react-jest-vanillacss-test

### System Info
Bug:
```shell
 FAIL  src/App.test.tsx
  ● Test suite failed to run
Styles were unable to be assigned to a file. This is generally caused by one of the following:
    - You may have created styles outside of a '.css.ts' context
    - You may have incorrect configuration. See https://vanilla-extract.style/documentation/setup

    1 | import { style } from "@vanilla-extract/css";
    2 |
 > 3 | export const pageContainer = style({
       |                                   ^
    4 |   width: "100vw",
```

**Comment by subingp** [comment]
@kishek2000  This is not an issue in vanllia-extract, this more a configuration problem in your jest config. Please update  config with styleMock as below

```
{
  "jest": {
    "moduleNameMapper": {
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$": "<rootDir>/__mocks__/fileMock.js",
      "\\.(css|less)$": "<rootDir>/__mocks__/styleMock.js"
    }
  }
}
```
Please visit https://jestjs.io/docs/webpack#handling-static-assets for more detailed documention.

**Comment by kishek2000** [comment]
> 

Hey @subingp , appreciate your response and help!
Bit confused about how to apply this - so I've added this config into my project package.json and I've added a __mocks__ folder with a stub string import for fileMock.js and an empty import for styleMock.js as per the link you provided.

I'm still encountering issues with Jest unable to parse unexpected token, any tips?
<img width="2038" alt="Screen Shot 2022-01-08 at 8 27 08 pm" src="https://user-images.githubusercontent.com/59722356/148639141-6627be30-4b5d-441d-a61c-72bf42f24625.png">

**Comment by rtkaaho** [comment]
If you are using jest, you need to use babel to transpile your code including vanilla-extract. See https://vanilla-extract.style/documentation/setup/#test-environments

**Comment by mattcompiles** [comment]
@rtkaaho is right. As specified in the [test environment setup](https://vanilla-extract.style/documentation/setup/#test-environments) you need to enable the babel plugin to get vanilla-extract working in jest. You also need to be wary of `.css` file mocking which a lot of jest setups have, however you'll want to remove it not add it. I've also added some info to the docs about how to resolve this as well.

I'm going to close this as I think the docs have all the required info to get you setup, however if you have further issues getting started feel free to ask questions in discord or github discussions.

**Comment by jcarenza** [comment]
@mattcompiles is there a way to conditionally have styling mocking? is it possible to evaluate inside a `styleMock.js` if it is vanilla extract (and opt out) or if it is something else that does need style mocking (in order to migrate incrementally to VE). for something like styled-components, targeting a filename/path doesn't seem doable.  or some other way to interop between the two?
