### ISSUE TITLE
HMR doesn't work in freshly installed Vite Vanilla-Extract React App

### ISSUE THREAD

**Issue by Erik-Sovereign** [seek-oss/vanilla-extract#578]
### Describe the bug
HMR doesn't work in a newly installed App with React, Vanilla-Extract and Vite. All packages are on the newest version. Instead the page reloads and React loses its State whenever Test.css.ts is safed.
`yarn create vite vite-vanilla-extract-test --template react-ts `
No error messages were displayed (vite: logLevel: "error", vanillaExtractPlugin identifiers:debug). 

### Link to reproduction
[Link](https://github.com/Erik-Sovereign/vite-vanilla-extract-test)

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:
  System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Memory: 5.70 GB / 15.57 GB
  Binaries:
    Node: 14.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.14.15 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.43)
  npmPackages:
    @vanilla-extract/css: ^1.6.8 => 1.6.8
    @vanilla-extract/vite-plugin: ^3.1.2 => 3.1.2
    vite: ^2.8.0 => 2.8.0

**Comment by drywolf** [comment]
I found out about vanilla-extract just yesterday and was excited to try it, but immediately ran into the same issue 😿

**Comment by drywolf** [comment]
I found a workaround by forcing the vite-plugin to an older version, calling:
`yarn add @vanilla-extract/vite-plugin@2.1.3`

and in the vite.config.ts using:
`vanillaExtractPlugin({devStyleRuntime: "vanilla-extract"})`

(this option for the plugin is only available in the older version, versions >= 3.0.0 had this option removed)

So this issue might still be related to #346 #422

**Comment by mattcompiles** [comment]
Running that reproduction locally I see hot reloading working fine. I can update the background color and everything updates as expected. 

I'm wondering if this issue is specific to windows. @drywolf are you also running windows?

**Comment by drywolf** [comment]
Yes I am on Windows 10 @mattcompiles

**Comment by jemgold** [comment]
@drywolf thanks - that worked for me too. I'm just following along Mark's video https://www.youtube.com/watch?v=23VqED_kO2Q with a simple Vite (react-ts) setup; changing anything in my theme didn't update variables. rolling back to 2.1.3 worked :)

**Comment by tamanugi** [comment]
I'm facing same issue in 3.1.6.
And version downgrade to 2.1.3, it worked!

system info
----

  System:
    OS: macOS 11.3.1
    CPU: (8) arm64 Apple M1
    Memory: 145.59 MB / 16.00 GB
    Shell: 3.3.1 - /opt/homebrew/bin/fish

  Binaries:
    Node: 16.14.0 - ~/.asdf/installs/nodejs/lts-gallium/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 8.3.1 - ~/.asdf/plugins/nodejs/shims/npm

  Browsers:
    Chrome: 101.0.4951.64
    Safari: 14.1

**Comment by mimoid-prog** [comment]
Still the same issue for `"@vanilla-extract/vite-plugin": "^3.1.6"`. It is not reacting to styles changes.
As suggested above, installing older version helped.

**Comment by mattcompiles** [comment]
Hey Everyone, 

I think there's multiple different issues being discussed here. Some should hopefully be fixed in `3.1.7`. 

If everyone could re-test on the new version and report back here that'd be great. 👍

**Comment by tamanugi** [comment]
@mattcompiles 
 

this comment's issues  fixed on `3.1.7`  🎉 
https://github.com/seek-oss/vanilla-extract/issues/578#issuecomment-1133020076

Thank you😍

**Comment by mattcompiles** [comment]
Closing this as I believe the issue was resolved in `@vanilla-extract/vite-plugin: 3.1.7`. Please open a new issue if you experience any similar issues going forward.

**Comment by cpakken** [comment]
I'm running "@vanilla-extract/vite-plugin": "^3.2.1" and HMR doesn't seem to be working. Tried switching to version 2.1.3 and HMR works fine.

Basic setup
- vite react template using `pnpm create vite` (react-ts option).
- Substituted `.App-header` with a vanilla-extract version.
- switch backgroundColor
- save
- See full reload on 3.2.1, and HMR on 2.1.3

Link to repo
https://github.com/cpakken/vite-vanilla-extract-test-hmr-not-working
