### ISSUE TITLE
Support "createStyles" and "createGlobalStyles" api like React Native?

### ISSUE THREAD

**Issue by kingback** [seek-oss/vanilla-extract#595]
## current

```ts
export const container = style({
  margin: 10
});

export const title = style({
  width: 200
});

export const text = style({
  color: 'red'
});

globalStyle(`${container} p`, {});
```

## after

```ts
const container = style({
  margin: 10
});

export const styles =  createStyles({
  container,
  title: {
    width: 200
  },
  text: {
    color: 'red'
  }
});

createGlobalStyles({
  [`${container} p`]: {}
});
```

Makes it easy to migrate style code from react native project.

**Comment by mattcompiles** [comment]
You could definitely build something like this within your own app, however I don't think this is something we'd ever support first class. I'd say there are probably other libraries more suited to react-native style sharing than vanilla-extract.
