### ISSUE TITLE
Unable to use `recipe` with `sprinkles`

### ISSUE THREAD

**Issue by RafalFilipek** [seek-oss/vanilla-extract#604]
### Describe the bug
When you use `sprinkles` function inside `recipe` function call, invalid values are passed to generate CSS code.

### Link to reproduction
https://codesandbox.io/s/fervent-waterfall-ujfyvh?file=/src/App.css.ts:106-115

Here you can find simple reproduction. Code was forked from the official sprinkles example  (from docs).
As you can see, there are three buttons (`App.tsx`). Each button should have proper text color (styles are in `App.css.ts`). Unfortunately, generated classes looks like this:

![image](https://user-images.githubusercontent.com/80960/156236658-546dbb3a-6f7e-4820-81d1-049790b84a62.png)

![image](https://user-images.githubusercontent.com/80960/156236707-3bdde1c4-8301-4ea7-bb32-2ea5212fb038.png)

### System Info

`@vanilla-extract/babel-plugin`: `1.1.3`
`@vanilla-extract/css`: `1.6.8`
`@vanilla-extract/recipes`: `0.2.3`
`@vanilla-extract/sprinkles`: `1.3.3`
`@vanilla-extract/webpack-plugin`: `2.1.4`

Thank you for your time,

Rafał

**Comment by ctotheameron** [comment]
`sprinkles()` returns a class string, so you can't use it the way you're trying to.

I've forked and updated your sandbox like:

```typescript
export const button = recipe({
  base: [{ fontSize: 20 }, sprinkles({ backgroundColor: "green" })],
  variants: {
    variant: {
      primary: sprinkles({ backgroundColor: "blue" }),
      secondary: sprinkles({ backgroundColor: "red" })
    }
  }
});
```

https://codesandbox.io/s/blissful-cdn-e5zlcd?file=/src/App.css.ts

**Comment by RafalFilipek** [comment]
I was tricked by example on this page https://vanilla-extract.style/documentation/recipes-api/ because it has only one property in each `sprinkles` call :)

Thank you :)
