### ISSUE TITLE
Does not seems to work with Angular 11

### ISSUE THREAD

**Issue by one-aalam** [seek-oss/vanilla-extract#61]
Hi, Thank you for creating such a cool CSS pre-processor. Seeing that vanilla-extract loves typescript, just like Angular does I was very interested in getting it working with an Angular project. I [customised](https://www.npmjs.com/package/@angular-builders/custom-webpack#Custom-webpack-browser) the Webpack settings as Angular CLI tries to own the Webpack config, made necessary changes in [angular.json](https://github.com/one-aalam/ng11-starter-kit/commit/5857832fa334213350b7e8549b80a82db0143d79)(the first two files) and applied necessary changes in the [webpack.config.js](https://github.com/one-aalam/ng11-starter-kit/blob/main/webpack.config.js) but the project is not compiling post the changes

<img width="980" alt="ve" src="https://user-images.githubusercontent.com/532906/116506066-07ac4780-a8da-11eb-922f-caca32901ab4.png">

Without [this](https://github.com/one-aalam/ng11-starter-kit/blob/main/angular.json#L41) change, the errors are even more. 

**Repo URL**
https://github.com/one-aalam/ng11-starter-kit

**Comment by mattcompiles** [comment]
Hey Bud,

We're using [template-literal-types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-1/#template-literal-types) here which was released in TypeScript 4.1. What version of TypeScript are you running?

**Comment by one-aalam** [comment]
Thanks! I was running on `4.0.5`. Updated it to `4.1.3` now, and met with another error.

<img width="1495" alt="ts-err" src="https://user-images.githubusercontent.com/532906/116517542-bd809180-a8ec-11eb-882a-41b60eb39ec8.png">

**Comment by markdalgleish** [comment]
Can you share a repo for us to look at?

**Comment by mattcompiles** [comment]
This issue was resolved in #95. If there's any further issues please open another issue with a reproduction. 👍
