### ISSUE TITLE
is there any plan to expose compile API in intergration package? 

### ISSUE THREAD

**Issue by brianshen1990** [seek-oss/vanilla-extract#625]
Currently, it said `This package is not intended for public consumption.` 

is there any plan to expose compile API in intergration package so that we can test integrations with other tools like rollup?

**Comment by mattcompiles** [comment]
The integration package is just a set of utilities to help build plugins to various bundlers. Each one is slightly different and have different requirements. When we say the package isn't meant for public consumption, we mean that it shouldn't be needed for general use of vanilla-extract.

However, if you want to try building your own plugin then please go ahead and use the utilities it supports. We don't document the package though so you'll have to read source code to work out what it does. There is a compile API already available from it. However that's only part of building a new plugin.
