### ISSUE TITLE
babel-plugin failed to compile type Modifiers on Import Names.

### ISSUE THREAD

**Issue by harisraharjo** [seek-oss/vanilla-extract#636]
### Describe the bug
Babel-plugin breaks when reading a line with type modifiers on import Names ( `import {type Sometype} from "..."` ) which was introduced in typescript `4.5`. The error says `Syntax error: Unexpected token, expected ","`. The app uses Nextjs, so I can't confirm about the others.

### Link to reproduction:
https://github.com/harisraharjo/ve-babel-plugin-repro

### System Info
```
"@vanilla-extract/babel-plugin": "^1.1.5",
"@vanilla-extract/css": "^1.6.8",
"@vanilla-extract/next-plugin": "^2.0.1",
"@vanilla-extract/sprinkles": "^1.4.0"
```

**Comment by sillysillyc** [comment]
any solution？

**Comment by askoufis** [comment]
@sillysillyc The reproduction is gone, but it's likely that they were locked to an older version of babel that didn't support TS 4.5 syntax. `@vanilla-extract/babel-plugin` is no longer required for integrations, so it can be removed. Please open a new issue if you've found a reproducible bug.
