### ISSUE TITLE
ReferenceError: __webpack_require__ is not defined

### ISSUE THREAD

**Issue by LekoArts** [seek-oss/vanilla-extract#637]
### Describe the bug

Hi!

I'm not sure yet if this is a bug in webpack or in vanilla-extract, but I haven't seen this problem 5 days ago when I did test it out with https://github.com/gatsbyjs/gatsby/pull/35166. I've now re-run our example site https://github.com/gatsbyjs/gatsby/tree/master/examples/using-vanilla-extract and it fails with these kinds of errors:

```shell
ERROR in ./src/styles/404.css.ts
Module build failed (from ./node_modules/@vanilla-extract/webpack-plugin/loader/dist/vanilla-extract-webpack-plugin-loader.cjs.js):
ReferenceError: __webpack_require__ is not defined
    at eval (webpack-internal:///./src/styles/404.css.ts:1:1)
    at eval (<anonymous>)
    at Object../src/styles/404.css.ts (/Users/lejoe/code/work/gatsby/examples/using-vanilla-extract/src/styles/404.css.ts:21:1)
    at __webpack_require__ (/Users/lejoe/code/work/gatsby/examples/using-vanilla-extract/src/styles/404.css.ts:67:42)
    at /Users/lejoe/code/work/gatsby/examples/using-vanilla-extract/src/styles/404.css.ts:123:37
    at /Users/lejoe/code/work/gatsby/examples/using-vanilla-extract/src/styles/404.css.ts:126:12
    at Script.runInContext (node:vm:139:12)
    at Script.runInNewContext (node:vm:144:17)
    at Object.module.exports [as default] (/Users/lejoe/code/work/gatsby/examples/using-vanilla-extract/node_modules/eval/eval.js:71:12)
    at Object.processVanillaFile
(/Users/lejoe/code/work/gatsby/examples/using-vanilla-extract/node_modules/@vanilla-extract/integration/dist/vanilla-extract-integration.cjs.dev.js:108:50)
    at
/Users/lejoe/code/work/gatsby/examples/using-vanilla-extract/node_modules/@vanilla-extract/webpack-plugin/loader/dist/vanilla-extract-webpack-plugin-loader.cjs.dev.js:60:38
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at processImmediate (node:internal/timers:437:9)
```

I've tested it out with older Gatsby versions, back to 4.9.0, same error. So I currently suspect that it might be a webpack/vanilla-extract issue?

I've also tried pinning vanilla-extract to older versions but still no dice.

```
"@vanilla-extract/babel-plugin": "1.1.4",
"@vanilla-extract/css": "1.6.7",
"@vanilla-extract/webpack-plugin": "2.1.5",
```

### Link to reproduction

https://github.com/gatsbyjs/gatsby/tree/master/examples/using-vanilla-extract

Run `yarn` and then `yarn develop`.

### System Info

```node
  System:
    OS: macOS 12.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 406.86 MB / 16.00 GB
    Shell: 5.8.1 - /opt/local/bin/zsh
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.21.0 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  npmPackages:
    @vanilla-extract/css: ^1.6.8 => 1.6.8
    @vanilla-extract/webpack-plugin: ^2.1.6 => 2.1.6
```

**Comment by leithonenglish** [comment]
Will we be getting a fix for `dev` soon? 🙏

**Comment by 72636c** [comment]
I performed some lockfile surgery and I think I've narrowed this down to [eval@0.1.7](https://www.npmjs.com/package/eval/v/0.1.7). Can you try locking to [eval@0.1.6](https://www.npmjs.com/package/eval/v/0.1.6)?

**Comment by michaeltaranto** [comment]
> I performed some lockfile surgery and I think I've narrowed this down to [eval@0.1.7](https://www.npmjs.com/package/eval/v/0.1.7). Can you try locking to [eval@0.1.6](https://www.npmjs.com/package/eval/v/0.1.6)?

Adding a resolution to pin to `eval@0.1.6` fixes my repro. Digging into a comparison between the two versions. Thanks for sharing the info!

**Comment by LekoArts** [comment]
Yeah, pinning `eval` to `0.1.6` also fixes my reproduction.

Here's the diff of the change: https://diff.intrinsic.com/eval/0.1.6/0.1.7

**Comment by michaeltaranto** [comment]
Fix available in `@vanilla-extract/integration` @ `v3.0.1`.

**Comment by LekoArts** [comment]
`eval@0.1.8` was published, we should try if that fixed it (I can try later myself if no one gets to it)

**Comment by goodwin64** [comment]
> Fix available in @vanilla-extract/integration @ v3.0.1

@michaeltaranto seems like we don't use this dependency directly in our monorepo. How can I test whether it resolves the issue?

From `package.json` files:
```
// package 1:
        "@vanilla-extract/babel-plugin": "^1.1.5",
        "@vanilla-extract/next-plugin": "^2.0.1",
        "@vanilla-extract/webpack-plugin": "^2.1.6",

// package 2:
        "@vanilla-extract/css": "^1.6.8",
        "@vanilla-extract/css-utils": "^0.1.2",
        "@vanilla-extract/recipes": "^0.2.1",
        "@vanilla-extract/sprinkles": "^1.4.0",
```

**Comment by goodwin64** [comment]
Oh, I see in `yarn.lock` that `@vanilla-extract/babel-plugin` depends on the `@vanilla-extract/integration`:

```
"@vanilla-extract/babel-plugin@^1.1.5":
  version "1.1.5"
  resolved "https://registry.yarnpkg.com/@vanilla-extract/babel-plugin/-/babel-plugin-1.1.5.tgz#dcd1cd33979a7162135d3fc94a977b533764cf1d"
  integrity sha512-wt2Sxgt2ZzslwwTDaZFGdrf0yUsoadOwAM73R6Gzv/1UJSzIdThVss/5JSwVO4RKvnus+0I1Iiq8pWqSJsRbCQ==
  dependencies:
    "@babel/core" "^7.13.10"
    "@babel/template" "^7.12.13"
    "@vanilla-extract/integration" "^3.0.0"
```

This plugin needs to bump the `integration` dependency to the working one.

**Comment by michaeltaranto** [comment]
Yep, all vanilla-extract deps in your lock file need to be bumped to latest versions.

**Comment by goodwin64** [comment]
Always thought `yarn.lock` should be generated automatically :confused: 

But will try that, thanks!

**Comment by michaeltaranto** [comment]
It is generated automatically, but if you have previously "locked' to bad sub-dependencies you will need to relock.

Sorry I wasn't suggesting you manually edit your lock file
