### ISSUE TITLE
While testing sprinkles is not a function for the Component which uses sprinkles in runtime

### ISSUE THREAD

**Issue by klaskow** [seek-oss/vanilla-extract#664]
### Describe the bug

I created repo based on preact-cli (https://github.com/preactjs/preact-cli) with typescript template (https://github.com/preactjs-templates/typescript).

I created in it 4 Buttons with tests. 3 tests are working properly. One of them (ButtonSprinklesRuntime.test.ts), where the function createSprinkles in runtime is used, does not work because sprinklesFn is not a function:

```sh
Uncaught [TypeError: (0 , _buttonSprinklesRuntimeCss).sprinklesFn is not a function]
```

The same issue appears with the same components prepared for NextJS. To the repo I added logs/nextjs.log which contains the whole trace but from NextJS. Almost the same logs is printed to the console when run tests with `npm run test:watch` from the reproduction repo.

Am I missing something in configuration or is it a bug in Sprinkles?

### Link to reproduction

https://github.com/klaskow/preact-testing-vanilla-extract

### System Info

```node
  System:
    OS: Linux 5.17 Ubuntu 22.04 LTS 22.04 (Jammy Jellyfish)
    CPU: (4) x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
    Memory: 5.25 GB / 15.51 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
  Browsers:
    Chrome: 100.0.4896.127
    Firefox: 99.0.1
  npmPackages:
    @vanilla-extract/css: ^1.7.0 => 1.7.0
    @vanilla-extract/sprinkles: ^1.4.0 => 1.4.0
    @vanilla-extract/webpack-plugin: ^2.1.8 => 2.1.8
```

**Comment by mattcompiles** [comment]
The issue here is that `jest-preset-preact` automatically replaces imports ending with `.css` with a mock file. This was a common solution for getting CSS modules working in test environments however it won't work with vanilla-extract. The tests in your reproduction are not actually executing any vanilla-extract code at all. 

You'll need to override this setting and allow imports ending in `.css` to run as normal to get this working.
