### ISSUE TITLE
Testing with Vitest

### ISSUE THREAD

**Issue by domosedov** [seek-oss/vanilla-extract#666]
Hello, any help how test vanilla-extract with Vitest?

Demo: [Stackblitz](https://stackblitz.com/edit/vitejs-vite-xtnslf)

i have an error with `npm run test`
```
 FAIL  src/components/button/button.test.tsx [ src/components/button/button.test.tsx ]
Error: Styles were unable to be assigned to a file. This is generally caused by one of the following:

- You may have created styles outside of a '.css.ts' context
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/setup
```

**Comment by coloradocolby** [comment]
Yep I'm seeing the exact same thing. My configuration is as follows:

```
/// <reference types="vitest" />
/// <reference types="vite/client" />

import react from "@vitejs/plugin-react";
import { vanillaExtractPlugin } from "@vanilla-extract/vite-plugin";

export default {
  plugins: [react(), vanillaExtractPlugin()],
  test: {
    globals: true,
    environment: "happy-dom",
    setupFiles: ["./setup-test-env.ts"],
    include: ["./src/**/*.{test,spec}.tsx"],
    watchIgnore: [".*\\/node_modules\\/.*", ".*\\/build\\/.*"],
  },
};
```

**Comment by AndrewLeedham** [comment]
Hey All. I ran into this a few weeks ago, it was a pain to debug. The issue is with some code being run in ESM and some in CJS so the file scopes stuff is split across 2 separate modules and therefore cannot see each-others local variables. Long story short you need to include the following in your Vite config:
```javascript
{
  // ...
  test {
    deps: {
      fallbackCJS: true,
    }
  }
}
```
https://vitest.dev/config/#deps

See fixed fork here: https://stackblitz.com/edit/vitejs-vite-1fmagr?file=vite.config.ts

**Comment by frankwallis** [comment]
It looks to be related to this issue: https://github.com/vitest-dev/vitest/issues/747

**Comment by gkiely** [comment]
@markdalgleish Might be worth adding @domosedov solution to the docs? It does print this error message by default with vitest.

<img width="941" alt="image" src="https://user-images.githubusercontent.com/1948935/178068882-5ed871c3-5d95-451c-81e3-72bf8e03c744.png">

**Comment by AndrewLeedham** [comment]
This has been properly fixed with https://github.com/vanilla-extract-css/vanilla-extract/pull/833

**Comment by AndrewLeedham** [comment]
@swernerx it was released in [@vanilla-extract/css@1.9.1](https://github.com/vanilla-extract-css/vanilla-extract/releases/tag/%40vanilla-extract%2Fcss%401.9.1), working for me.

**Comment by swernerx** [comment]
Interesting, I am on 1.9.2, and it is definitely not working without the `fallbackCJS` hack.

**Comment by scarf005** [comment]
on `@vanilla-extract/css@^1.17.4`, having exact same issue.
