### ISSUE TITLE
"ReferenceError: $RefreshReg$ is not defined" when using React + Yarn Workspaces

### ISSUE THREAD

**Issue by Jpoliachik** [seek-oss/vanilla-extract#679]
### Describe the bug

I encountered this problem in our Yarn Workspaces setup, where a shared `design-system` package uses Vanilla Extract to house token values, it creates a theme, and also contains shared React components. These are all exported through a barrel `index.ts` file. 

We have two React apps that import from this - a Create React App and a Next App. Both apps encounter this error during compilation when importing from `design-system` in development mode. The CRA app can 'bypass' it by disabling Fast Refresh altogether, but this isn't an option for Next. 

In my testing, I believe this error only occurs when a React component is exported alongside the Vanilla Extract `createTheme` in a separate workspace package. In testing I was able to `createTheme` in a standalone package and import and use it successfully in the Next app package. And I was able to export standalone React components with applied Vanilla Extract `style()` without issue. Only when using React components _and_ `createTheme` in the same package did I encounter this issue. 

```
error - ./pages/home.css.ts
NonErrorEmittedError: (Emitted value instead of an instance of Error) ReferenceError: $RefreshReg$ is not defined
```

Any ideas what might be causing this? 

### Link to reproduction

I created a simple repo to reproduce:
https://github.com/Jpoliachik/ve-workspace-react-issue

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 12.2
    CPU: (8) arm64 Apple M1
    Memory: 658.64 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Safari: 15.3
```

**Comment by jose-elias-alvarez** [comment]
We've investigated this further and have narrowed it down `ReactRefreshWebpackPlugin`, which is built into Next.js (disabling it is unfortunately [not supported](https://github.com/vercel/next.js/issues/13268)). There's some more context [here](https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/TROUBLESHOOTING.md#usage-with-indirection-like-workers-and-js-templates), but basically, when we import a component that uses Vanilla Extract using an import path that is *not* in PascalCase, the error pops up. 

[This commit](https://github.com/jose-elias-alvarez/nextjs-vanilla-extract-example/commit/225a54b39eba45f67464c07a0753e2464145d639) in a sample repo should hopefully illustrate the issue. Strictly speaking, I don't think this is a Vanilla Extract issue, but it does severely limit the library's compatibility with Next.js. Is there any way we can work around this?

**Comment by JCMais** [comment]
Having the same issue, is having a separate build step the only solution?

**Comment by imbhargav5** [comment]
This may help you. 

I was able to side step this error by importing directly from a file that didn't export components. 

So perhaps this will work for you.

```javascript
import {theme} from 'design-system/theme.css'
```

**Comment by alexchantastic** [comment]
@imbhargav5 thank you! That worked for me.

**Comment by m-shaka** [comment]
I'm using Next.js and had the same error. `next dev` with webpack production mode do well and hot reloading is still working, while I'm not sure if there is any performance trade-off.

```js
// next.config.js
/** @type {import('next').NextConfig} */
const nextConfig = {
  webpack: (config, { dev }) => {
    return {
      ...config,
      mode: dev ? 'production' : config.mode,
    }
  }
};
```
