### ISSUE TITLE
Please revert "feat: validate media queries (#651)" (32f309fa)

### ISSUE THREAD

**Issue by nodegin** [seek-oss/vanilla-extract#683]
### Describe the bug

This commit uses a 3rd party lib `css-mediaquery` which the [date last published is 8 years ago](https://www.npmjs.com/package/css-mediaquery),

it will not validate newer CSS mediaqueries, like `prefers-reduced-motion`

in modern repositories it will raise errors.

<img width="886" alt="Screen Shot 2022-05-13 at 16 24 38" src="https://user-images.githubusercontent.com/8536244/168232674-fca471fa-0dbc-4327-83be-50fe89e71546.png">

**Comment by mattcompiles** [comment]
Your example media query is invalid. You should be wrapping the `prefers-reduced-motion` expression in parentheses e.g. `(prefers-reduced-motion: no-preference)`. 

Check out the examples here: https://web.dev/prefers-reduced-motion/#working-with-the-media-query
