### ISSUE TITLE
Inline properties definitions in `defineProperties` are inferred as `string[]`

### ISSUE THREAD

**Issue by FedericoBiccheddu** [seek-oss/vanilla-extract#688]
### Describe the bug

After picking up an "old" project, all inline properties got inferred as `string[]` all of a sudden. Before they were correctly inferred as defined values.

### Link to reproduction

https://codesandbox.io/s/cocky-cray-p5zc3b?file=/src/theme.css.ts

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: Linux 5.13 Alpine Linux
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
    Memory: 8.41 GB / 15.57 GB
    Container: Yes
    Shell: 1.34.1 - /bin/ash
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
  npmPackages:
    @vanilla-extract/css: ~1.7.0 => 1.7.0 
    @vanilla-extract/sprinkles: ~1.4.1 => 1.4.1 
    @vanilla-extract/vite-plugin: ~3.1.6 => 3.1.6 
    vite: ~2.9.9 => 2.9.9
```

**Comment by graup** [comment]
I see the same thing in your sandbox, but I cannot reproduce it in [TS Playground](https://www.typescriptlang.org/play?ts=4.4.4#code/JYWwDg9gTgLgBAbzgEwKYDNgDtUAUoRiqzCoDOANHAMZSoCGMqAymFNgNYA25cAvnHQEQcAEQABAG70swLl3oBaVAA8YUetRgB6Mm048yogNwBYAFAXqELGXh7NqOAF5EFuHCw3UALjgAGCnc4MhB6eT9RABYwFVEg8w8QVGRgAFcQSIAOWPjghSgAc18xAEYANlzg7W04VBhqADoLPjNLc2tbeDo9GzJgSTwCIhJeVzRMHHxCYhhSMgAKBGDO1Lm+v2XEjzgQCAAjORKEPgSduBh6fZ4YTbFxZNT6UUiyWlRULDgZZDgFkGwigA7sBkDAABZ+ADs5RyKgAlKJ+GcdmgyBwYIQ7hJHsBnq93p9vlhfv9ASCwZC4KV-AAmGIIpF8YKnYITehpLgwADCNjWwBskT2hx4eW2bBmozIm2CHlSegUAE8-ABtUReHDxMToHhxKiia4QagcLWibBcbCoUQAXRRHh1qgAIsA6FoBVhVaICEDTdYuBksDa7XAAFZpOzAdCK3lYJix1WynaiOx0BrgsXnDyiB0qRR2eiwDOZ0TUT5MKBF87Z3XKEmVpMOUuKAsQNJ14NZxuoRT7epAj6BxO2xPhYCFLAASSYIGlcDVKfq1HT+pzecuhf1pdjxFNq8+yCDibA9GQqSwhQAKliQsfS8Hj6fsIUAEIQGCYzI3xz3k9nwoAGQwW4vzvI9fyfAAlMdwWArtExqOoGmabZWW2MhwWgCEflnLZzgfP9PXwp8rzAU0iPPV93wgEAyPA89APQGBaMfc8oMKGDD22DxyMKAANQi6IAoDmL-NiOOHLi4B4gBNASWMvQgRKfSiP04vCFFLKdUBnT0wwjKMYzjJj9VHcctJnG0WRaeE2isPp4D9aAyBcNxtgNf1uwAVn8F4xAAYgwdBynQdAi3ctJuxpHzIj85Be3odArRRcLu1pfxov8-Z0DixKwsKDRFUUKF0t80Q-IAZihKJSk80o8oKxQshKmLSnQWkAE5Kvq+hCva5r-NKQaslpKFRGqWpF2Q1oLDsroaAgLhoGmEY5jGFAMEtZbZnmJYVj5YB1lsGVJItdiYAAWQgNBNlQ85kALDhLuuxB7lxfExAWNgMGIMhFEcqA8yXbSSnuqAOERfgWRRdlOR5fbDsiU6YKepLgglFb5mO85-r8f7KETfZNA4fLWxJXGFqc+CJqQqzzD4GyZvMVRIFgea5r0dgsG4Nb3kYFh9C5wwFh6SBbAGIZJVWyh5sWqAtqlBn2gQqcAHJnPoOBCggK64FBBgLggOoVBZ+AIScVhOe55yYEVIgDYgCxmcwi5bfNgWrZc3AC3oZJyzIAAeG2iAgdAb0twwAD4VX8a02iAA).

There must be something wrong with the setup. TS version, config, anything else that affects types?

**Comment by FedericoBiccheddu** [comment]
I did reopen the project today and now they're working again... :man_shrugging: I am on `typescript` `4.6.4`.

VSCode: 
```
Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:23:40.286Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.13.0-44-generic
```

Maybe was the VSCode version? I think I got an update in the last 11 days.

I share my `tsconfig` just in case is needed.

<details><summary>tsconfig.json</summary>
<pre>
<code>
{
  "compilerOptions": {
    "allowJs": false,
    "alwaysStrict": true,
    "composite": true,
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "noEmitOnError": true,
    "noErrorTruncation": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noImplicitAny": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "preserveSymlinks": true,
    "removeComments": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "sourceRoot": "./source/",
    "strict": true,
    "strictFunctionTypes": true,
    "strictNullChecks": true,
    "sourceMap": true,
    "target": "esnext",
    "useDefineForClassFields": true,
    "useUnknownInCatchVariables": true,
  },
  "include": [
    "./source/**/*"
  ],
  "exclude": [
    "./source/**/*.test"
  ]
}
</code>
</pre>
</details>
