### ISSUE TITLE
Add more examples to documentation

### ISSUE THREAD

**Issue by pakholeung37** [seek-oss/vanilla-extract#697]
This is really a great library. However, there are so many API that sometimes I am confused about which should I use. Hope there will be more examples or best practices to show when to use those APIs, or more official examples will be provided.

**Comment by lodisy** [comment]
Second this

**Comment by mattcompiles** [comment]
Going to close this after the shipping the new docs site. https://vanilla-extract.style 

If there is still missing information people want to know then you can open a separate issue.
