### ISSUE TITLE
Vite: Sourcemap warning suppression

### ISSUE THREAD

**Issue by mcclayton** [seek-oss/vanilla-extract#699]
### Describe the bug
When building an app using vite and vanilla extract, and when the [build.sourcemap](https://vitejs.dev/config/#build-sourcemap) vite config option is set to true, I receive a bunch of sourcemap warnings. 
i.e.
```
vite v2.9.9 building for production...
✓ 15216 modules transformed.
rendering chunks (2)...Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
Sourcemap is likely to be incorrect: a plugin (vanilla-extract) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help
...
```
The vanilla extract docs list a way to supress this warning for esbuild:
https://github.com/seek-oss/vanilla-extract#esbuild

but I haven't found a way to suppress them for Vite. Would love to be able to suppress these if possible.

### System Info

Output of `npx envinfo --system --npmPackages @vanilla-extract/css,@vanilla-extract/webpack-plugin,@vanilla-extract/esbuild-plugin,@vanilla-extract/vite-plugin,@vanilla-extract/sprinkles,webpack,esbuild,vite --binaries --browsers`:

```node
  System:
    OS: macOS 12.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.75 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.asdf/installs/nodejs/16.13.1/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.3.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 101.0.4951.64
    Firefox: 100.0.2
    Safari: 15.3
  npmPackages:
    @vanilla-extract/css: ^1.6.8 => 1.6.8
    @vanilla-extract/vite-plugin: ^3.1.6 => 3.1.6
    @vanilla-extract/webpack-plugin: ^2.1.5 => 2.1.10
    vite: ^2.9.9 => 2.9.9
```

**Comment by roginfarrer** [comment]
The rollup plugin generates a similar warning https://rollupjs.org/guide/en/#warning-sourcemap-is-likely-to-be-incorrect

**Comment by mattcompiles** [comment]
I'm not sure creating sourcemaps for VE files is possible, as the transform that occurs is not an AST transform. I agree this warning is not ideal though. Not sure what the recommended approach is here. Is there a way to tell Vite/Rollup that this transform won't create a sourcemap and to not warn about it? Or am I wrong about sourcemaps being a viable option?

**Comment by graup** [comment]
I think it may be difficult to create exact sourcemaps, but it might be possible to at least provide a mapping to the relevant `style()/createSprinkles()/globalStyle()/etc` call in the source .css.ts? This would be better than nothing as it helps to find the correct file.

**Comment by mattcompiles** [comment]
@graup Do you have any ideas on how to implement it?

**Comment by graup** [comment]
For now, it should be possible to suppress the warnings by returning empty source maps. Haven't tested it but I think in the transform functions we just need to change

```js
return processVanillaFile(...)
```

to

```js
return {
  code: await processVanillaFile(...),
  map: { mappings: '' }
}
```

I'll have a think about if we can return more meaningful maps there.
