### ISSUE TITLE
Should support tree-shaking in production

### ISSUE THREAD

**Issue by pakholeung37** [seek-oss/vanilla-extract#700]
if you import style from app.css.ts
```typescript
// app.css.ts
export const styleA = style({
  display: 'flex'
})
export const styleB = style({ // no used
  display: 'flex'
})
```
```typescript
// App.tsx
import { styleA } from './app.css.ts'
export const App = () => {
   return <div className={styleA}/>
```
It's surprising that vanilla extract doesn't do any tree-shaking which means both styleA and styleB will all include in the CSS bundle

Maybe related to these code
https://github.com/seek-oss/vanilla-extract/blob/aebf9349371d631a38145df70c7de40643843554/packages/integration/src/processVanillaFile.ts#L94-L99

**Comment by guilhermedeandrade** [comment]
I have no idea about how hard it is to support tree-shaking to be honest. However, is this really an issue? I mean, if you have unused styles, you would want to simply remove them, right? Or am I missing something here?

**Comment by pakholeung37** [comment]
@guilhermedeandrade I know we have sprinkle but say you are building some utility classes
```typescript
// utility.css.ts
export const px = style({
  fontSize: '1px'
})
export const px_0 = style({
  fontSize: '0px'
})
export const px_0_5 = style({
  fontSize: '0.125rem'
})
export const px_1 = style({
  fontSize: '0.25rem'
})
...
```
But you don't eventually use all of them. In this case, tree-shaking will help.

For now, I am using [PurgeCSS](https://github.com/FullHuman/purgecss) to do the job, I works fine!

**Comment by guilhermedeandrade** [comment]
@pakholeung37 I see your use case, thanks for sharing! 

I don't know how the maintainers feel about it, but I'd say that your approach of using PurgeCSS is what makes more sense to me. I mean, I don't think that this really should be addressed by vanilla-extract itself.

**Comment by mattcompiles** [comment]
Tree shaking is a bundler feature, we can't implement it inside of vanilla-extract. However, vanilla-extract does generate code that can be tree shaken so if that's not working it may be your setup (look into the `sideEffects` config) or an issue with your bundler. 

It's possible there could be a problem within vanilla-extract itself but it would be related to the specific integration and you haven't mentioned what bundler you're using. I'm going to close this but if you have reason to believe vanilla-extract is doing something to prevent tree shaking from working then open an issue with a reproduction of the issue.

**Comment by ddhp** [comment]
> For now, I am using [PurgeCSS](https://github.com/FullHuman/purgecss) to do the job, I works fine!

Hi I am trying to get tree shaking to work with PurgeCSS, but it would remove all the style.

Here is the minimal reproduce repo
https://stackblitz.com/edit/vercel-next-js-cidu1b?file=README.md

Have I missed something?

next.js native css-module is working fine

Thanks!

**Comment by pakholeung37** [comment]
@ddhp I did not use PurgeCSS as a plugin. Instead I wrote a script and run it after build. Check my repo
https://github.com/pakholeung37/loft-mix/blob/dc027d5e146876de65ad942204d8445d3d19eba0/packages/main/scripts/purgecss.js
