### ISSUE TITLE
Default variants don't use compound variants

### ISSUE THREAD

**Issue by lesha1201** [seek-oss/vanilla-extract#703]
### Describe the bug

Default variants ignores compound variants. It's only possible to use a compound variant when explicitly set all needed variants. For example,

```jsx
// Compound (compound-1)
{
  variants: {
    variant: 'filled',
    color: 'red',
  },
  style: {
    backgroundColor: 'red',
    color: 'white',
  },
}

// Compound is applied
<Button variant="filled" color="red" /> // --> <button class="button compound-1" />
```

But when we have default variants, it doesn't use compound variant even if all needed variants are set:

```jsx
// Default variants
{
  defaultVariants: {
    variant: 'filled',
    color: 'red',
  },
}

// Compound isn't applied
<Button /> // --> <button class="button" />
```

I would expect that it uses the compound variant in this case.

### Link to reproduction

https://codesandbox.io/s/vanilla-extract-compound-issue-u39hdg

**Comment by mattcompiles** [comment]
This had me confused for a minute. It's not that compound variants don't work for default values, and more that compound variants don't take defaulting into account when an explicit undefined value is passed in e.g. `variant: undefined`. This occurs in your example as you're forwarding optional props to recipes in your component. 

Will try fix this ASAP.

**Comment by lesha1201** [comment]
@mattcompiles I see. Thank you for clarifying. Now I wonder whether this actually should be fixed. After the fix, it's not possible to turn off default variant by providing nullish value. Probably, in my case I just should use default props in React component instead of `defaultVariants`.

Another way is to add options to the returned function of `recipe` so it can be set how to treat values in such case.

I'm not sure whether a case with turning off default variant is valid or not. What do you think?
