### ISSUE TITLE
@vanilla-extract/vite-plugin regression for v3.1.5 in monorepo setup

### ISSUE THREAD

**Issue by danielberndt** [seek-oss/vanilla-extract#714]
Hi there, when upgrading I've noticed that imports in a mono-repo setup do not work any more.
Here's a what I'm doing:
```
import "@cdx/web/src/global-styles.css"; // a css.js file
```

my vite config looks like this:

```
    config.resolve = {
      alias: {
        "@cdx/web": resolve(__dirname, "../../web-app"),
      },
    };
```

Here's what the network tab's output looks like in @vanilla-extract/vite-plugin v3.1.4:
![3 1 14](https://user-images.githubusercontent.com/856386/171608876-a3e4d110-b205-4087-8d77-b7a063ec61a2.png)

and here for v3.1.5:
![3 1 15](https://user-images.githubusercontent.com/856386/171608929-9a50f225-39c8-4e37-a486-a51e542e0436.png)

I'm not 100% sure whether this is enough information already, it's a bit hard to setup a more isolated use case as storybook is involved, but I definitely can try to dig up more if needed :)

**Comment by mattcompiles** [comment]
Hey mate, 

Sorry for the issues. Unfortunately, I can't tell what's wrong without more info. Ideally add a small github reproduction and I'll try take a look.

**Comment by rickdunkin** [comment]
This sounds very similar to [this issue](https://github.com/seek-oss/vanilla-extract/issues/689) that includes a [reproduction repo](https://github.com/dkzlv/vanilla-extract-repro)

**Comment by danielberndt** [comment]
Thanks @rickdunkin yes, this looks like it should be the same issue indeed!
Seeing that a PR is ready for it, I'm closing this issue here and will re-open with a reproduction should it still be present ✌️
