### ISSUE TITLE
Importing themes across projects in a monorepo

### ISSUE THREAD

**Issue by jackmccloy** [seek-oss/vanilla-extract#727]
### Describe the bug

howdy y'all! inside of my monorepo, i'm trying to define vanilla-extract themes one project and use them in another. i've been struggling with this for a couple of days, and was hoping someone could take a look at what i'm doing and point out what i'm doing wrong

here's a repo where the error can be easily reproduced, along w/ repro instructions https://github.com/jackmccloy/vanilla-extract-monorepo-issue

thanks! any help is appreciated

### Reproduction

https://github.com/jackmccloy/vanilla-extract-monorepo-issue

### System Info

```shell
System:
    OS: macOS 12.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 24.91 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.15.0 - /usr/local/opt/node@16/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.5.5 - /usr/local/opt/node@16/bin/npm
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 90.0.2
    Safari: 15.5
```

### Used Package Manager

yarn

### Logs

```shell
(in the browser console)

Uncaught Error: Styles were unable to be assigned to a file. This is generally caused by one of the following:

- You may have created styles outside of a '.css.ts' context
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/setup
    at getFileScope (vanilla-extract-css-fileScope.browser.esm.js:25:11)
    at createVar (vanilla-extract-css.browser.esm.js:245:7)
    at vanilla-extract-css.browser.esm.js:293:12
    at walkObject (vanilla-extract-private.esm.js:34:20)
    at walkObject (vanilla-extract-private.esm.js:36:20)
    at walkObject (vanilla-extract-private.esm.js:36:20)
    at createThemeContract (vanilla-extract-css.browser.esm.js:292:10)
    at index.mjs:3:21
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/seek-oss/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mattcompiles** [comment]
Hi 👋 

When I load your repo and run your instructions I was having different issues but I think I can see the issue anyway. You're compiling your `themes` package into a single file (with tsup) without using the vanilla-extract plugin. This is likely why you're getting the above error. You'll either need to setup tsup to compile the vanilla-extract code into CSS files at the package level, or get your storybook to look at the source code of the package rather than the compiled output.

**Comment by jackmccloy** [comment]
That put me on the right path! fiddling around a bit w/ `tsup` did the trick, and now i'm back on track. Thanks so much for the quick response (and great work in general)

**Comment by danstans** [comment]
@jackmccloy do you mind updating your repo with the change that made this work? also exploring using vanilla-extract in a turborepo setting and having some difficulties getting setup.

**Comment by jackmccloy** [comment]
hey @danstans - I made the change in a private repo that I can't share, the repo I linked to was a minimal repro of the issue. looking back at my commits, the change mostly boiled down to packaging css at the package level by adding this to the `exports` key in my package's `package.json`

```
"./dist/index.css": {
  "import": "./dist/index.css",
  "require": "./dist/index.css"
}
```

**Comment by lamualfa** [comment]
`tsup` doesn't resolve the local path. You need to use the exact path you use when importing the `*.css.ts` file.

# Example

**`src/index.css.ts`**
```ts
import { style } from '@vanilla-extract/css'

export const headerClass = style({})
```

**`src/index.ts`**
```ts
import { headerClass } from './index.css'
```

**`tsup.config.ts`**

**This will work**. `tsup` will not bundle the `src/index.css.ts` into a single file.

```ts
import { defineConfig } from 'tsup'

export default defineConfig({
  bundle: true,
  external: ['./index.css.ts']
})
```

or if you don't define all of `*.css.ts` in the `external` config one by one, you can use a RegeExp instead:

```ts
import { defineConfig } from 'tsup'

export default defineConfig({
  bundle: true,
  external: [/^\.\/[\w-_]+\.css$/]
})
```

**This won't work.** `tsup` still bundles the `src/index.css.ts` into a single file.

```ts
// INVALID CONFIGURATION

import { defineConfig } from 'tsup'

export default defineConfig({
  bundle: true,
  external: ['src/index.css.ts']
})
```
