### ISSUE TITLE
TypeError: (0 , theme_css_1.sprinkles) is not a function

### ISSUE THREAD

**Issue by Hervera** [seek-oss/vanilla-extract#731]
### Describe the bug

Running tests using Jest, doesn't recognize functions called from .css.ts files.

<img width="551" alt="Screenshot 2022-06-14 at 20 28 31" src="https://user-images.githubusercontent.com/25223709/173662663-3e4c0b0c-4c82-469c-aa4d-63791e9dc731.png">

I have tried to add the babel plugin in `babel.config.js` and  'identity-obj-proxy' in `jest.config.ts`, but the error doesn't disappear
```
{
  "plugins": ["@vanilla-extract/babel-plugin"]
}
```

```
moduleNameMapper: {
    '\\.(css|less|scss|sass)$': 'identity-obj-proxy',
  },
```

### Reproduction

https://github.com/seek-oss/vanilla-extract#test-environments

### System Info

```shell
Error: Uncaught [TypeError: (0 , index_css_1.default) is not a function]
TypeError: (0 , theme_css_1.sprinkles) is not a function
```

### Used Package Manager

yarn

### Logs

```shell
Error: Uncaught [TypeError: (0 , index_css_1.default) is not a function]

TypeError: (0 , theme_css_1.sprinkles) is not a function
```

### Validations

- [X] Check that there isn't [already an issue](https://github.com/seek-oss/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [x] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mattcompiles** [comment]
The docs state that you need to **remove** the file mocks/identity proxy from your config, not add them. This is stated in the [test environments setup](https://vanilla-extract.style/documentation/setup/#test-environments) section of the docs.

**Comment by Hervera** [comment]
I removed the file mocks/identity proxy from my config and enabled the babel plugin as stated in [test environments setup](https://vanilla-extract.style/documentation/setup/#test-environments), but I am still facing these errors
```
 console.error
    Error: Could not parse CSS stylesheet
```

<img width="710" alt="Screenshot 2022-06-24 at 09 38 38" src="https://user-images.githubusercontent.com/25223709/175487316-77f2d505-989f-4853-8f59-88a64d265f8b.png">

**Comment by Hervera** [comment]
Thanks, It has worked. It was all about my configurations. To solve it, I had to use the same configuration you have on the repo, by replacing ` '^.+\\.(ts|tsx|js|jsx)$': 'ts-jest', ` with  `'^.+\\.(ts|tsx|js|jsx)$': ['babel-jest', { configFile: './babel.config.json' }],` in  jest.config.ts.
