### ISSUE TITLE
Assigning numerical values in themes

### ISSUE THREAD

**Issue by raoz** [seek-oss/vanilla-extract#74]
Omitting `as any` in the following example results in a type error. Also cannot set them as numbers inside `createGlobalTheme`.
```
export const vars = createGlobalTheme(":root", {
  fontFamily: {
    title: "'Lato', sans-serif",
    body: "'Raleway', sans-serif",
  },
  fontWeight: {
    title: "700",
    body: "400",
  },
});

globalStyle("html, body", {
  fontFamily: vars.fontFamily.body,
  fontWeight: vars.fontWeight.body as any,
});
```

**Comment by mattcompiles** [comment]
I believe the styles issue was fixed in [0.4.0](https://github.com/seek-oss/vanilla-extract/blob/master/packages/css/CHANGELOG.md#040).

The theme issue has been [raised before](https://github.com/seek-oss/vanilla-extract/pull/43#issuecomment-826427488).
