### ISSUE TITLE
`::before` and `::after`

### ISSUE THREAD

**Issue by TheKnarf** [seek-oss/vanilla-extract#75]
Can I style pseudo classes like `::before` and `::after`? If so it would be nice with an example in the docs.

**Comment by loliver** [comment]
Use `selectors`.

```
const testClassName = style({
  selectors: {
    '::before': {
      ...
    }
  }
})
```

**Comment by michaeltaranto** [comment]
Simple pseudos can also be used at the top level of the style object:

```tsx
const testClassName = style({
  '::before': {
    ...
  }
})
```

It is documented under the [style api](https://github.com/seek-oss/vanilla-extract#style), but might need more prominence/clarity.
> CSS Variables, **_simple pseudos_**, selectors and media/feature queries are all supported.

Something we'll consider. Thanks.

**Comment by moroshko** [comment]
@michaeltaranto What's the recommended approach with dynamic `content`?

For example, say an `Input` component gets a `prefix` as a prop, e.g.: `<Input prefix="$" ... />`

and, I'd like to render a `div` with this pseudo element:
```
"::before": {
  content: `"${prefix}"`,
  ...
}
```

**Comment by michaeltaranto** [comment]
For this i would recommend using the [assignInlineVars](https://vanilla-extract.style/documentation/dynamic-api/#assigninlinevars) api from the [dynamic package](https://vanilla-extract.style/documentation/dynamic-api/). Then you can setup your styling rules in a vanilla extract style sheet and export the variable reference. The component can then import the variable reference and assign its value dynamically.

Here is a [quick sandbox demo](https://codesandbox.io/s/assigninlinevars-example-i8hp0?file=/src/App.tsx:1149-1227).

Hope that helps.

**Comment by moroshko** [comment]
Very helpful, thanks Mike!
