### ISSUE TITLE
NextJS compile especially slow on M1 Mac silicon

### ISSUE THREAD

**Issue by foolmoron** [seek-oss/vanilla-extract#771]
### Workarounds to try in your codebase!
It looks like this ticket isn't going to be addressed anytime soon, so I'll just share what we did in our codebase to massively mitigate this. Reduced compile time by 25x.
1. Move as many props as possible to unconditional `sprinkles` definitions (i.e. `defineProperties()` without `conditions` prop).
2. Patch VE to remove all the dev string concatenation. This is our patch using yarn. We left in the option to use the strings if an env is defined:
```diff
diff --git a/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js b/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js
index 6e40061..10283a2 100644
--- a/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js
+++ b/node_modules/@vanilla-extract/css/dist/vanilla-extract-css.cjs.dev.js
@@ -177,11 +177,13 @@ function generateIdentifier(debugId) {
   var fileScopeHash = hash__default["default"](packageName ? "".concat(packageName).concat(filePath) : filePath);
   var identifier = "".concat(fileScopeHash).concat(refCount);
 
-  if (adapter_dist_vanillaExtractCssAdapter.getIdentOption() === 'debug') {
-    var devPrefix = getDevPrefix(debugId);
+  if (process.env.VANILLA_EXTRACT_DEV_PREFIX) {
+    if (adapter_dist_vanillaExtractCssAdapter.getIdentOption() === 'debug') {
+      var devPrefix = getDevPrefix(debugId);
 
-    if (devPrefix) {
-      identifier = "".concat(devPrefix, "__").concat(identifier);
+      if (devPrefix) {
+        identifier = "".concat(devPrefix, "__").concat(identifier);
+      }
     }
   }
```

### Describe the bug

We have a large NextJS codebase using VE that has progressively moved more and more of our CSS to VE over the past 2 months.

We've seen NextJS compile times on M1s get much slower as we adopted VE more (30s to 60s to 120s to 400s). Intel Macs and Windows do not have the issue - compiles are 30s for them.

We looked at 2 compile times, both of which got slower:
1. Starting up a next server and waiting for it to start serving pages
4. Going to a page that imports our VE components package and waiting until Next finishes the compile

FYI We have 74 `css.ts` files and several hundreds of elements with custom styles. And we use the standard `withVanillaExtract` plugin with no options.

Have you seen anything like this? Any tips to make this better for M1?

#### Workarounds attempted
In our NextJS page, removing the import to VE components eliminates the slowdown. It's around 3s after that. But of course we need the imports at some point.

I tried stubbing out all the `style()` and `recipe()` and other calls in our code to return empty strings. That brought the compile down to 150s. That is still much slower than the Intel compile.

After the stubbing, I removed the `withVanillaExtract` plugin and that brought the compile time down to 30s as expected. So I suspect it's something to do with the webpack stuff.

[See comments for more details on the following workarounds]

Installed an x64 version of node using Rosetta, and that brought compiles down to 50s.

Then I patched the VE webpack plugin to cache the result of processVanillaFile(), and that brought things down to 30s as expected.

### Reproduction

Can't provide since it's private code. The problem only seems to happen on non-minimal projects!

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (10) arm64 Apple M1 Max
    Memory: 78.61 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 3.2.0 - ~/.nvm/versions/node/v16.10.0/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: 102.0.1
    Safari: 15.6
  npmPackages:
    esbuild: 0.14.11 => 0.14.11 
    webpack: 5.73.0 => 5.73.0
```

### Used Package Manager

yarn

### Validations

- [X] Check that there isn't [already an issue](https://github.com/seek-oss/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ianmcgregor** [comment]
Is it potentially related to https://github.com/seek-oss/vanilla-extract/issues/374 that was recently re-opened?

(It has comments about very slow builds on mac silicon CPUs)

**Comment by foolmoron** [comment]
2 more workarounds that seemed to work:

First I installed node using Rosetta. See "macs with m1 chip" here https://github.com/nvm-sh/nvm#macos-troubleshooting. That brought the compile time down to around 50s.

Then I patched `@vanilla-extract/webpack-plugin/loader/dist/vanilla-extract-webpack-plugin-loader.cjs.dev.js` to add an in-memory cache like for `processVanillaFile()`. This reduced the compile down to 30s as expected!
```
const vanillaCache = new Map()
```
```
const result = vanillaCache.get(this.resourcePath) ?? await integration.processVanillaFile(/* etc */)
```

**Comment by foolmoron** [comment]
I also profiled that function and found that some files take 1ms to process, while others can take 25000-80000ms.

The difference is the slow ones import a `tokens.css.ts` that we have which calls `createGlobalTheme(':root')` with around 12 objects and around 200 props total. It also calls `createThemeContract()` with around 50 props, and `createTheme()` with that contract and an obj of 50 props.

**Comment by TheMightyPenguin** [comment]
I was doing some local testing and found out:
* Importing tokens (created with `createGlobalTheme`) in a .css.ts file increases the time it takes to compile it. I did a small benchmark in a small react app, with 200 .css.ts files. When not importing tokens in these, it took ~20 seconds in average, and when importing tokens from all of these, it took ~30 seconds in average.
* When combining many properties with conditions in Sprinkles, this also increases compile times (this made sense, we're moving our excess sprinkles into unconditional properties)

**Comment by TheMightyPenguin** [comment]
Also, our project runs fine on intel based macs or windows machines, it only happens with M1 macs, I'll take a look as it could be one of the dependencies in vanilla extract having issues with M1 macs!

**Comment by zackshackleton** [comment]
We ran into a similar issue at my company. This issue only appeared on M1 macs in debug/dev builds , not during production builds. The issue appeared to be too many node threads were being spun up and never had a chance to finish. Strangely enough, commenting out all of the debug string concatenation lines (shown below) we were able to get back normal build times however we lost out on debug names in the browser console. 

`identifier = "".concat(devPrefix, "__").concat(identifier);`

**Comment by jordie23** [comment]
We're finding VE slow on Mac Intels, M1s and Linux machines. It's across the board much slower than what we had previously (theme-ui). Was considering opening an issue too but haven't had time to actually compile metrics.  

Obviously there's a different between compile time and run time implementations, but it can be painful to dev on it when nextjs takes 30s to render a page when using the dev server.

**Comment by jordie23** [comment]
If you run `export DEBUG=vanilla*` then you'll see al the vanilla extract debug logs, which has timings along with it. 

I'm reguarly seeing `+3s` and `+4s` for what are fairy small files. 

a snippet of what I mean

```
  vanilla-extract:loader:"a.css.ts" Completed successfully +4s
  vanilla-extract:loader:"b.css.ts" Completed successfully +4s
  vanilla-extract:loader:"c.css.ts" Completed successfully +4s
  vanilla-extract:loader:"d.css.ts" Completed successfully +2s
  vanilla-extract:loader:"e.css.ts" Completed successfully +4s
  vanilla-extract:loader:"f.css.ts" Completed successfully +3s
```

Seems to hint at the webpack loader?

**Comment by mattcompiles** [comment]
I've got some theories on this issue but without an actual reproduction it's very hard for me to work on it. 

Would someone be willing to submit a reproduction repo? Doesn't need to be super slow, just enough to showcase the issue.

**Comment by mattcompiles** [comment]
I've got an experimental version of the webpack/next plugin that may help with this issue. If anyone would like to test it and report back that would be really useful. Note, there's a known small memory leak in this implementation. I doubt it'll cause much of a problem but will hopefully get addressed if we choose to use this approach. 

Just install whichever plugin you're already using:

<p>Version: <code>@vanilla-extract/next-plugin@0.0.0-alternative-webpack-loader-20228910529</code></p>
<pre><code>pnpm add @vanilla-extract/next-plugin@alternative-webpack-loader</code></pre>
<p>Version: <code>@vanilla-extract/webpack-plugin@0.0.0-alternative-webpack-loader-20228910529</code></p>
<pre><code>pnpm add @vanilla-extract/webpack-plugin@alternative-webpack-loader</code></pre>

**Comment by foolmoron** [comment]
With those packages I get nearly the exact same compile times as I do with the patch in my first post (11.5 startup, 23.5s large route compile). So that looks good to me!

**Comment by mattcompiles** [comment]
@foolmoron I assume that's with the debug IDs turned on?

**Comment by momin-tf** [comment]
@mattcompiles Yes I removed my patch and added the new package branches. Although maybe I need to reinstall node modules to be sure?

**Comment by AlexGalays** [comment]
Yeah there's something going on with M1 chips in particular. I doubt it has something to do with webpack as we don't use it. What I know at the moment:

Cold start for mac intel chip: 15s

Cold start on mac M1: 2.5 minutes (328 modules total) reloading is 400ms
If I remove the vite `vanillaExtractPlugin`, cold start on mac M1: 2 seconds (293 modules total, most are ts/tsx)

Is there any way I can help profiling this?

**Comment by zackshackleton** [comment]
While trying to debug what was going on, I threw in some console logs before and after the devPrefix string concatenations. With that, I was able to see all the threads being spun up and console logging out before the concatenation, and then it just hangs. It seems as if it's choking out the machine by spinning up too many threads at once.

**Comment by AlexGalays** [comment]
For now I swapped the identifier strategy to `short`: 

```ts
vanillaExtractPlugin({ identifiers: "debug" })
```

And the cold start time goes from 2.5 minutes to 4 seconds. lol.

**Comment by jisooyu** [comment]
@mattcompiles, thanks a lot. After the installation, the speed is noticeably improved.

**Comment by hanshank** [comment]
@mattcompiles - I'm working on an application where we noticed this issue causing 6x slower compilation times when using the "debug" option. Was this ever fixed in a newer version of `@vanilla-extract/next-plugin` or is the only way to fix it to stop using the `debug` param in `createVanillaExtractPlugin` ?
