### ISSUE TITLE
Using sprinkles in a recipe doesn't output the correct css variable

### ISSUE THREAD

**Issue by gyfchong** [seek-oss/vanilla-extract#775]
### Describe the bug

When creating recipe variants utilising sprinkles to apply values to CSS attributes, the resulting output does not use the correct CSS vars. Instead it tries to place class names in the CSS itself.

### Reproduction

https://codesandbox.io/s/quiet-sunset-v709yq?file=/src/App.tsx

### System Info

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1 Pro
    Memory: 1.01 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 3.2.2 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Browsers:
    Chrome: 104.0.5112.79
    Firefox: 100.0.2
    Safari: 15.6
```

### Used Package Manager

yarn

### Validations

- [X] Check that there isn't [already an issue](https://github.com/seek-oss/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by benjervis** [comment]
The purpose of [sprinkles] is to "Generate a static set of custom utility classes and compose them ... statically at build time", so the output of the sprinkles function is a series of classnames.

If you look at the example [docs for recipes], where the sprinkles functions are used directly, you can see that sprinkles is actually used at the variant level, not the individual property level.

```ts
  // ...

  variants: {
    color: {
      neutral: sprinkles({ background: 'neutral' }),
      brand: sprinkles({ background: 'brand' }),
      accent: sprinkles({ background: 'accent' })
    },
    size: {
      small: sprinkles({ padding: 'small' }),
      medium: sprinkles({ padding: 'medium' }),
      large: sprinkles({ padding: 'large' })
    }
  },
  // ...
```
The good news is that sprinkles already does most of what you're trying to do. You can pass multiple properties to the sprinkles function, so

```diff
variants: {
    tone: {
-      primary: {
-        color: sprinkles({ color: "white" }),
-        background: sprinkles({ background: "green-500" })
-      },
+     primary: sprinkles({ color: "white", background: "green-500" }),
```

For what you want to do with the borders, you should use your vars directly, and compose up that style with the sprinkles you do have.

```ts
secondary: style([
  sprinkles({ color: "green-500", background: "white" }),
  `1px solid ${vars.color["green-500"]}`,
]),
```

I forked your codesandbox, take a look and let me know if that answers your questions.

https://codesandbox.io/s/amazing-frog-jck5lf?file=/src/App.css.ts

[sprinkles]: https://vanilla-extract.style/documentation/packages/sprinkles
[docs for recipes]: https://vanilla-extract.style/documentation/packages/recipes/

**Comment by gyfchong** [comment]
Thanks @benjervis!
