### ISSUE TITLE
Support for Astro

### ISSUE THREAD

**Issue by arthur-fontaine** [seek-oss/vanilla-extract#795]
### Describe the bug

_This issue relates to this discussion: https://github.com/seek-oss/vanilla-extract/discussions/678_

Using Astro, which uses Vite under the hood, the styles are not applied.

The style is not at all imported, but the class names are correctly generated.
```html
<!-- from the reproduction example -->
<html>
   <!-- ... -->
  <body>
   <!-- ... -->
    <li class="Card__s70yhy1 astro-4Q53QFQW">
   <!-- ... -->
```

According to [this issue](https://github.com/withastro/astro/issues/2536#issuecomment-1122823724) (https://github.com/withastro/astro/issues/2536#issuecomment-1122823724):
> The vanilla-extract plugin works with Vite's default SPA templates, but doesn't work with Astro which renders purely server side. Not all Vite plugins work in Astro for this reason.

### Reproduction

https://stackblitz.com/edit/vanilla-extract-support-for-astro

### System Info

```shell
all
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/seek-oss/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

---

### Edit (24/08/2022)

Using a React component with the `client:visible` directive works. On the screenshot, only the first card is a React component.

<img width="948" alt="Capture d’écran 2022-08-24 à 21 10 34" src="https://user-images.githubusercontent.com/57626613/186503189-19433b58-bbd4-4361-b2cc-cab8d5e7aec7.png">

**Comment by Thesoreon** [comment]
Hello everyone 👋,

To clarify, Arthur has made this issue so we can discuss possible solutions and help the VE team introduce a solution. We want to help them, so support for Astro is there ASAP, but since I'm just getting into the internal workings of VE & Astro, it's a bit hard to pinpoint and mainly introduce a fully working solution.

I'll post every update in the search for the solution here.

**Comment by matthewp** [comment]
We don't really support CSS-in-JS at all in Astro at the moment. There's this issue where people are trying to figure out a solution: https://github.com/withastro/astro/issues/4432

The issue @arthur-fontaine is linking too isn't really true any more, Astro can work with most Vite plugins now. I think the question would be, how does Astro know that a style is associated with a given page?

I'm not exactly sure how Vanilla extract works, but if your Vite plugin makes the CSS look like it's an `import` statement then it might "just work", but perhaps that isn't the case right now.

**Comment by arthur-fontaine** [comment]
The code to inject the css code is generated in the [load](https://github.com/seek-oss/vanilla-extract/blob/master/packages/vite-plugin/src/index.ts#L90) method, but the method is stopped at [line 93](https://github.com/seek-oss/vanilla-extract/blob/master/packages/vite-plugin/src/index.ts#L93) if the file is not found in the `cssMap`.
The `cssMap` is fed at [line 210](https://github.com/seek-oss/vanilla-extract/blob/master/packages/vite-plugin/src/index.ts#L210), but the method is stopped at [line 139](https://github.com/seek-oss/vanilla-extract/blob/master/packages/vite-plugin/src/index.ts#L139) if the mode is SSR. That's why the css works when we use the `client:visible` directive.

So (unless I'm mistaken), we have to find a way to compile the file (ts + vanilla-extract) and feed `cssMap`.

**Comment by FredKSchott** [comment]
Update: Astro now supports vanilla-extract! Table in https://github.com/withastro/astro/issues/4432 has been updated
