### ISSUE TITLE
`@container` queries don’t work with Vite

### ISSUE THREAD

**Issue by joshuabaker** [seek-oss/vanilla-extract#829]
### Describe the bug

The `@container` query is not compiled to valid CSS.

Related to #807

### Reproduction

https://codesandbox.io/s/vite-react-ts-forked-iwgfgh?file=/src/app.css.ts

### System Info

```shell
System:
    OS: Linux 5.13 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
    Memory: 4.49 GB / 62.72 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 14.19.3 - ~/.nvm/versions/node/v14.19.3/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.19.3/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.19.3/bin/npm
  npmPackages:
    @vanilla-extract/css: 1.9.0 => 1.9.0
    @vanilla-extract/vite-plugin: 3.5.0 => 3.5.0
    vite: ^2.2.3 => 2.3.3
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't [already an issue](https://github.com/seek-oss/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mattcompiles** [comment]
For container queries to work they must be in a valid container context using the `containerType` property. Vanilla-extract's output here is correct. See [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries) for more info. 

Btw your scenario is using a theme but not setting the `themeClass` anywhere in the document which means the vars won't have any values at runtime.

**Comment by joshuabaker** [comment]
Do [the docs](https://vanilla-extract.style/documentation/styling/#container-queries) need updating?

I’m seeing the same result when setting `containerType` (i.e. not getting applied).

```js
export const exampleStyle = style({
  color: 'white',
  background: 'blue',
  containerType: 'inline-size',
  '@container': {
    '(max-width: 500px)': {
      background: 'red',
    },
  },
});
```

**Comment by artemis-prime** [comment]
You're using the feature incorrectly here.

`containerType` would be set on **a parent** of the element that uses `@container`
