### ISSUE TITLE
Vite Storybook

### ISSUE THREAD

**Issue by joaogarin** [seek-oss/vanilla-extract#835]
### Describe the bug

I've been trying to write a components library based on Vanilla Extract using vite and then consume the library in a Next.js project

The problem is when running storybook (initialized first storybook with vite as documented in the site) I get the error : 

```
Styles were unable to be assigned to a file. This is generally caused by one of the following: 
- You may have created styles outside of a '.css.ts' context 
- You may have incorrect configuration. See https://vanilla-extract.style/documentation/setup
```

This was previously opened in [this issue
](https://github.com/seek-oss/vanilla-extract/issues/458) and somoone there seems to have the same problem.

The reproduction URL can be used to confirm what is happening. When running yarn build (vite by itself) it seems to work fine but something in the storybook is maybe missing, or misconfigured..I wonder what, the error was not really clear on what's missing.

The way I setup this was to start a vite storybook as documented in https://storybook.js.org/blog/storybook-for-vite/ and then added Vanilla extract

### Reproduction

https://github.com/joaogarin/cl-vanilla

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.4 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
    Memory: 2.39 GB / 15.29 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.20.0 - ~/.nvm/versions/node/v14.20.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.17 - ~/.nvm/versions/node/v14.20.0/bin/npm
  Browsers:
    Brave Browser: 99.1.36.116
    Chrome: 104.0.5112.79
    Firefox: 104.0
  npmPackages:
    @vanilla-extract/css: ^1.9.0 => 1.9.0 
    @vanilla-extract/vite-plugin: ^3.5.0 => 3.5.0 
    vite: ^3.1.0 => 3.1.3
```

### Used Package Manager

yarn

### Validations

- [X] Check that there isn't [already an issue](https://github.com/seek-oss/vanilla-extract/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by joaogarin** [comment]
I will close the issue now, I found the answer here https://github.com/seek-oss/vanilla-extract/discussions/371#discussioncomment-3676198 

The solution was to add the : 

```
 async viteFinal(config) {
    return mergeConfig(config, {
      plugins: [require("@vanilla-extract/vite-plugin").vanillaExtractPlugin()],
    });
  },
```

At the end of the main.js file in the `.storybook` folder

**Comment by gabrieloureiro** [comment]
This stop's working?
