### ISSUE TITLE
Dynamic composeStyles

### ISSUE THREAD

**Issue by Amareis** [seek-oss/vanilla-extract#85]
Since there is way to export functions from css.ts, why not to add possibility to create classnames string based on some runtime condition? It should enforce encapsulation of styles.

```ts
export const buttonStyles = dynamicVariants(style({
  //default styles
  background: 'white',
}),{ 
  //styles variants
  primary: style({background: 'green'}),
  disabled: style({
    background: 'gray',
    cursor: 'unset',
  })
})
```

And then...
```tsx
import {buttonStyles} from './styles.css.ts'

function SomeButton({primary, disabled}: {primary: boolean, disabled: boolean}) {
  return <button className={buttonStyles({primary, disabled})} />
}
```

**Comment by markdalgleish** [comment]
This is a cool idea. It's not something we feel needs to be in core, but if you're keen this could definitely be built as a library.

**Comment by Amareis** [comment]
So, i did it! https://github.com/Amareis/vanilla-classnames

**Comment by markdalgleish** [comment]
Oh, awesome! When I get a chance, I might add a libraries section to the readme. In the meantime, I have your work a shout out on Twitter 😄 https://twitter.com/markdalgleish/status/1389924046255497224

**Comment by Amareis** [comment]
Maybe just add it next to composeStyles, where is link to classnames?
