### ISSUE TITLE
Theme vars in globalStyle incorrect

### ISSUE THREAD

**Issue by loliver** [seek-oss/vanilla-extract#86]
Hey there, I'm having trouble getting `globalStyle` to apply the correct theme. I have the theme being applied to my `html` element but the `--var`s are being called from the first available theme className in the extracts file rather than the currently applied one.

Eg. `--palette-background-default__1tdsuw195` is being applied while the theme has `--palette-background-default__196i551195` available.

**Comment by mattcompiles** [comment]
Hey Bud. I'm sure exactly what you mean. Could you please replicate the issue in a repo or codesandbox for us to investigate?

**Comment by loliver** [comment]
I've managed to get working exactly what I'm doing locally in a codesandbox so obviously I'm missing something in my local setup. Will keep plugging away.
